### PR TITLE
METRON-861: Allow JVM args to be passed to CLI utilities

### PR DESCRIPTION
**Pull request by cestella**
## Contributor Comments
This is motivated by the fact that if one sets the acl's on the znodes that metron creates (e.g. /metron/topology/global) to read/write by metron (from the zkcli `setAcl /metron/topology/global sasl:metron:crwda`), then permissions prohibit the CLI tools from functioning because the JAAS config is not loaded.

This JIRA allows users to pass java properties to the CLI tools. While important for Kerberos, it's useful in general if one needs to adjust the heap required, etc.

To exercise this, do the following:
* Perform steps 1 through 17 of the [kerberos docs for vagrant](https://github.com/apache/incubator-metron/blob/master/metron-deployment/vagrant/Kerberos-setup.md)
* su to the metron user via `su - metron`
* Validate that you can dump the configs via `$METRON_HOME/bin/zk_load_configs.sh -m DUMP -z node1`
* Adjust the ACL for `/metron/topology/global` by
  * start zkcli by running `/usr/hdp/current/zookeeper-client/zookeeper-client -server node1`
  * adjust the acl via `setAcl /metron/topology/global sasl:metron:crwda`
* Destroy all existing tickets via `kdestroy`
* Validate that `$METRON_HOME/bin/zk_load_configs.sh -m DUMP -z node1` gives an error
* Validate that `JVMFLAGS="-Djava.security.auth.login.config=/home/metron/.storm/client_jaas.conf" $METRON_HOME/bin/zk_load_configs.sh -m DUMP -z node1` works

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron (Incubating).  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root incubating-metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  bin/generate-md.sh
  mvn site:site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommened that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by merrimanr** [comment]
Looks good to me.  This should be generally useful, even outside of the jaas use case.  

Would it make sense to namespace the JVMFLAGS environment variable so it's specific to Metron?  Not sure it matters much but it would make it more consistent with other environment variables we use.

**Comment by cestella** [comment]
You know, we definitely could.  I chose JVMFLAGS because it's what zookeeper calls them, but I'm open to other options.  Any suggestions?

**Comment by merrimanr** [comment]
METRON_JVMFLAGS?

**Comment by cestella** [comment]
I could get behind that.  Anyone else have other ideas?

**Comment by merrimanr** [comment]
+1

**Pull request closed without merging**
