### PR TITLE
METRON-538  Ensure proper shutdown, exceptions of integration test components

### PR DESCRIPTION
**Pull request by ottobackwards**
This is an effort to eliminate spam errors from our testing and hopefully improve our testing at the same time.

This PR will track the commits for this effort, and allow for timely comment and review.

So far the things we are looking for or seeing are

- problems with shutdown dependencies with the testing components like yarn and zk
- problems were we cannot completely mock out components.  Even if the tests pass, we are spammed with errors because of the attempts to connect to components that are part of the test because they are not needed.

Because of Apache Storm Issue STORM-1730
https://issues.apache.org/jira/browse/STORM-1730 it is not possible
to shutdown the LocalServer we use for storm without leaking threads.
These threads will output error messages when they 'wake up' and try to connect
with curator - to a zk embedded server that has already been shutdown.
This issue is fixed in Storm 1.0.3, but that is not released yet

Because of this unresolved issue  ZOOKEEPER-1237: https://issues.apache.org/jira/browse/ZOOKEEPER-1237 we also may see errors like
Running org.apache.metron.enrichment.integration.EnrichmentIntegrationTest

2016-11-09 22:25:50,293 ERROR [SyncThread:0] server.NIOServerCnxn (NIOServerCnxn.java:sendBuffer(178)) - Unexpected Exception: 

java.nio.channels.CancelledKeyException

	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)

	at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:77)

	at org.apache.storm.shade.org.apache.zookeeper.server.NIOServerCnxn.sendBuffer(NIOServerCnxn.java:151)

	at org.apache.storm.shade.org.apache.zookeeper.server.NIOServerCnxn.sendResponse(NIOServerCnxn.java:1081)

	at 

My goal is to keep this PR mergable with every commit as I go.  And as a bonus, each travis build will hopefully show the progress.

### CODE REVIEW

**Comment by ottobackwards** [comment]
OK,  This is some improvement, and I have identified a couple of issues with underlying components.  I am not sure we want to remove the logging or errors that is embedded in the production code.
ready for review.

**Comment by dlyle65535** [comment]
Hi @ottobackwards - thanks for taking this on, looking over the log, it looks like a huge improvement.

I am seeing a bunch of these:

2016-11-10 05:08:02 ERROR KafkaApis:103 - [KafkaApi-0] Error when handling request {topics=[enrichments]}

type errors in the log happening during various parser tests. What's your sense of these? Are these happening due to out of order set up and the tests are passing?

**Comment by ottobackwards** [comment]
I took a stab at that in my last commit, but have not checked the travis
log this morning, sorry.
Here is what I think is happening.

The parser tests do ( or did ) not create the ENRICHMENT topic when setting
up KafkaWithZK.  So, with auto create it will get created and work
eventually - but there is a chance that you will see errors for the
attempts to ‘trigger’ the auto creation.

I did not see those errors locally - only in travis.   When checking last
night against the travis log - i noticed them and tried creating the topic
to address.

I did not check the travis log this morning for it though, sorry.




On November 10, 2016 at 11:07:09, David Lyle (notifications@github.com)
wrote:

Hi @ottobackwards <https://github.com/ottobackwards> - thanks for taking
this on, looking over the log, it looks like a huge improvement.

I am seeing a bunch of these:

2016-11-10 05:08:02 ERROR KafkaApis:103 - [KafkaApi-0] Error when handling
request {topics=[enrichments]}

type errors in the log happening during various parser tests. What's your
sense of these? Are these happening due to out of order set up and the
tests are passing?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apache/incubator-metron/pull/344#issuecomment-259730544>,
or mute the thread

**Comment by ottobackwards** [comment]
Ok, looking at the log - my change did not resolve that issue.  I’ll keep
looking.



On November 10, 2016 at 11:43:08, Otto Fowler (ottobackwards@gmail.com)
wrote:

I took a stab at that in my last commit, but have not checked the travis
log this morning, sorry.
Here is what I think is happening.

The parser tests do ( or did ) not create the ENRICHMENT topic when setting
up KafkaWithZK.  So, with auto create it will get created and work
eventually - but there is a chance that you will see errors for the
attempts to ‘trigger’ the auto creation.

I did not see those errors locally - only in travis.   When checking last
night against the travis log - i noticed them and tried creating the topic
to address.

I did not check the travis log this morning for it though, sorry.




On November 10, 2016 at 11:07:09, David Lyle (notifications@github.com)
wrote:

Hi @ottobackwards <https://github.com/ottobackwards> - thanks for taking
this on, looking over the log, it looks like a huge improvement.

I am seeing a bunch of these:

2016-11-10 05:08:02 ERROR KafkaApis:103 - [KafkaApi-0] Error when handling
request {topics=[enrichments]}

type errors in the log happening during various parser tests. What's your
sense of these? Are these happening due to out of order set up and the
tests are passing?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apache/incubator-metron/pull/344#issuecomment-259730544>,
or mute the thread

**Comment by ottobackwards** [comment]
I am wondering if it isn’t :

TestUtils.waitUntilMetadataIsPropagated(scala.collection.JavaConversions.asScalaBuffer(servers),
topic, part, 5000);





On November 10, 2016 at 11:46:49, Otto Fowler (ottobackwards@gmail.com)
wrote:

ERROR KafkaApis:103 - [KafkaApi-0] Error when handling request

**Comment by ottobackwards** [comment]
Just to clarify, you see this with your local build/test?



On November 10, 2016 at 12:03:46, Otto Fowler (ottobackwards@gmail.com)
wrote:

I am wondering if it isn’t :

TestUtils.waitUntilMetadataIsPropagated(scala.collection.JavaConversions.asScalaBuffer(servers),
topic, part, 5000);





On November 10, 2016 at 11:46:49, Otto Fowler (ottobackwards@gmail.com)
wrote:

ERROR KafkaApis:103 - [KafkaApi-0] Error when handling request

**Comment by ottobackwards** [comment]
So,

I can only reproduce this in Travis, and even then it is not every parser
integration test.  I have tried a few different things, and have ended up
surprising the KafkaServer log4j logs while creating topics.  This seems to
have worked in the build.




On November 10, 2016 at 14:54:07, Otto Fowler (ottobackwards@gmail.com)
wrote:

Just to clarify, you see this with your local build/test?



On November 10, 2016 at 12:03:46, Otto Fowler (ottobackwards@gmail.com)
wrote:

I am wondering if it isn’t :

TestUtils.waitUntilMetadataIsPropagated(scala.collection.JavaConversions.asScalaBuffer(servers),
topic, part, 5000);





On November 10, 2016 at 11:46:49, Otto Fowler (ottobackwards@gmail.com)
wrote:

ERROR KafkaApis:103 - [KafkaApi-0] Error when handling request

**Comment by ottobackwards** [comment]
@dlyle65535 

OK, I think I know what is going on.

We kind of have a mess wrt the zookeeper stuff in the components.  I had originally taken a stab at untangling it, but had problems and reverted back and scaled back my attempts.  Now with my other PR for Yarn and ZKServerComponents - I'm going to try again.

The issue is that the KafkaWithZK component creates a zkserver, but it immediately goes out of scope.
I believe that causes the AdminUtils to fail looking up the brokers.

Now that I have a good ZKComponent ( from curator as opposed to the Kafka testing server one ) I'm going to try again

**Comment by ottobackwards** [comment]
please travis, this is all for you

**Comment by cestella** [comment]
This is *great*!  +1 for sure.  Super solid work, Otto!

**Comment by merrimanr** [comment]
Nice.  Big improvement.  Thanks Otto. +1

**Comment by nickwallen** [comment]
Really nice work, Otto.  Loving that I don't have to mentally ignore a bunch of exceptions that I know are erroneous.

**Pull request closed without merging**
