### PR TITLE
METRON-734 Builds failing because of MaxMind DB transitive dependency

### PR DESCRIPTION
**Pull request by justinleet**
The pure exclude solution.  Still being tested on Vagrant, but making it available for viewing.

### CODE REVIEW

**Comment by justinleet** [comment]
Spun up in Vagrant and saw enrichment data pass through (including Geo data) as expected.  In addition, GEO_GET in Stellar worked as expected for all data.

**Comment by cestella** [comment]
+1 by inspection.  Let's wait for a travis build and I move that we merge.

**Comment by ottobackwards** [comment]
+1, build and tests run (  mvn -q clean integration-test install && build_utils/verify_licenses.sh ), on machine that was failing every every time.

**Comment by nickwallen** [comment]
+1 Ran exactly what Travis does locally and it worked, where previously it failed consistently.

**Comment by ottobackwards** [comment]
This build is not even starting in travis :(

**Comment by kylerichardson** [comment]
+1 builds and all tests passing. Maybe close and reopen to kick travis?

**Comment by cestella** [comment]
@kylerichardson nah, travis hasn't gotten to it yet.  It's in the queue.

**Comment by kylerichardson** [comment]
gotcha, must just be backed up today

**Comment by justinleet** [comment]
Apparently https://issues.apache.org/jira/browse/METRON-728 occurs more frequently on travis than my local machine.

The Travis running on my personal account already succeed (https://travis-ci.org/justinleet/incubator-metron/builds/204210174)

I'll kick Travis and hopefully we aren't waiting 16 hours for a build

**Comment by cestella** [comment]
Given the fact that we are without a working build, the failure here is a known sporadic failure and the Travis queue seems to be very backed up lately, I move that we wait for 3 hours and then commit this PR on the basis of Justin's Travis results linked above.

Objections?

**Comment by kylerichardson** [comment]
+1 to proceeded with commit based on @justinleet's Travis results

**Comment by cestella** [comment]
I'm also going to tackle METRON-728 this morning, so we can avoid this in the future.

**Comment by merrimanr** [comment]
+1 on committing based on Justin's Travis results

**Comment by nickwallen** [comment]
> Given the fact that we are without a working build, the failure here is a known sporadic failure and the Travis queue seems to be very backed up lately, I move that we wait for 3 hours and then commit this PR on the basis of Justin's Travis results linked above.

+1 to commit based on previous successful travis run.

**Pull request closed without merging**
