### PR TITLE
Initial code for a website 

### PR DESCRIPTION
**Pull request by ddutta**
Base code from Jekyll. Working on incorporating the layout from ORC's pages. Also need a logo.

### CODE REVIEW

**Comment by cestella** [comment]
I'm not sure github pages is cool with the content being under 'site'.  Also, this seems to be the default layout for jekyll.  Maybe we want to wait to accept a pull request with the content as well as the layout?

**Comment by ddutta** [comment]
Thx cestella. This is temporary. Eventually it will go somewhere else like gh-pages. I am adding the content today/tonight and doing another push.

**Comment by ddutta** [comment]
Also this is for the Apache website not the github project page doc for which we need gh-pages or something ....

**Comment by ddutta** [comment]
Yes .... we could wait for 1-2 days for the layout and some base content

On Wed, Dec 9, 2015 at 2:16 PM, Casey Stella <notifications@github.com>
wrote:

> I'm not sure github pages is cool with the content being under 'site'.
> Also, this seems to be the default layout for jekyll. Maybe we want to wait
> to accept a pull request with the content as well as the layout?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-metron/pull/1#issuecomment-163416622>
> .
>



-- 
-Debo~

**Comment by omalley** [comment]
This isn't github pages, it is using the same tools (ie. Jekyll) as github pages to produce the html. Apache doesn't care how you produce the html, we just need to check the generated html into the asf-site branch and it will auto-magically replicate to http://metron.incubator.apache.org/

**Comment by omalley** [comment]
You should probably create an empty branch (named "site" maybe?) that has the source code for the site. I tried to build the site from your pull request, but it fails needs a Gemfile and with a missing header on the _posts/2015-12-09-welcome-to-jekyll.markdown.

**Comment by cestella** [comment]
I ran into that as well. Definitely need the Gemfile, but if you run jekyll
-serve from the site directory then the missing header seems to be ok. That
being said, I expect the contents of site should be moved up a directory so
things work from the base directory.

**Comment by omalley** [comment]
By the way, I filed METRON-1 for this. :)

**Comment by ddutta** [comment]
Thats very coool!

**Comment by ddutta** [comment]
Could someone please review the pull request? Instructions to build it are in BUILD.md

**Comment by lexholden** [comment]
+1. Works and looks like a good starting point.

**Comment by ddutta** [comment]
[METRON-1]

**Comment by omalley** [comment]
Why don't you pick one of the logos for now and update it when the community picks one in a few days?

You should fix the link the slides and use: http://www.slideshare.net/JamesSirota/cisco-opensoc
Use the embed code from slideshare:
```
<iframe src="//www.slideshare.net/slideshow/embed_code/key/GgFRMw4XulD4Lj" width="595" height="485" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/JamesSirota/cisco-opensoc" title="Cisco OpenSOC" target="_blank">Cisco OpenSOC</a> </strong> from <strong><a href="//www.slideshare.net/JamesSirota" target="_blank">James Sirota</a></strong> </div>
```

I guess for videos, I'd use:
https://www.youtube.com/watch?v=UKgjd4ttg8o

I'd suggest changing the highlights to blue.

**Comment by omalley** [comment]
Oh, you also have the ORC twitter on the news page, which probably not what you want. :)

**Comment by omalley** [comment]
The link to the jira should be: https://issues.apache.org/jira/browse/metron

The correct user mailing list for the "help" page is: user@metron.incubator.apache.org

The mailing lists on the "develop" page need to be updated.

**Comment by ddutta** [comment]
Thans a lot of for the comment Owen. The idea was to do small commits and get the baseline site merged. Then fix a lot of the content. Will do another commit tonight.

**Comment by cestella** [comment]
I left a comment on the [JIRA]( https://issues.apache.org/jira/browse/METRON-1?focusedCommentId=15058050&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15058050).

In general, are we commenting on pull requests or the JIRA?  They don't seem to be autopopulating between the two systems and this could get confusing fast.

**Comment by ddutta** [comment]
Many people might not have access to JIRA while everyone should be able to comment on github. What should we use?

**Comment by cestella** [comment]
Everyone should have the ability to comment or submit a JIRA.

**Comment by james-sirota** [comment]
Just posed something to the dev list about this.  Send me your ID and I'll add you

**Comment by ddutta** [comment]
JIRA ID=ddutta

**Comment by james-sirota** [comment]
Done. can you verify you have all the permissions you need?

**Comment by ddutta** [comment]
Done with the basic changes suggested by Owen. Please review.

**Comment by cestella** [comment]
I looked at the site, looks much better.  I had a couple comments:
* I'd drop the "Sample News" and "Welcome to Jekyll" post
* Under Develop, I'd add the project members as listed on the [wiki](https://cwiki.apache.org/confluence/display/METRON/Member+List)
* I believe the HTML must be in the root directory, not under site.  I'd recommend moving the contents of 'site' up a directory.
* The favicon.ico is still the ORC icon.

**Comment by ddutta** [comment]
Thx cestella
* dropped sample news etc. 
* the project members and a bunch of other material will be done in another content pull request, there is some other stuff I want to do too. This is not the last pull on website
* I changed the favicon for now to reflect the logo but I will do one more cleanup

**Comment by ddutta** [comment]
cestella: if you compare with the orc's directory structure, there is a directory called site for the code. Then there is a branch called asf_site where the generated HTML code is checked in. I have mimicked that. Did you by any chance see the asf_site under your directory? If so thats the generated code when you run jekyll.

**Comment by cestella** [comment]
Right, but if you look what's showing currently in http://metron.incubator.apache.org/, it's the index.html which is at the root of the asf-site branch.  Also, if you look at orc's git structure, the ASF branch has what is in effect the content of what's in the site directory here.  I'm not sure what the purpose of site directory is in the master branch for orc.

**Comment by ddutta** [comment]
Yes I need to check the generated files (from the asf_site target) into the asf_site branch of current code base. Then it will auto update.

**Comment by cestella** [comment]
Ahh, I get it.  There will be a followup pull request with that patch.  Got it.

**Comment by ddutta** [comment]
Thx for all your feedback .... hope you can +1 this and merge now.

**Comment by cestella** [comment]
I still see the welcome to jekyll post, can you remove it?

**Comment by ddutta** [comment]
Sorry but where are you seeing the jekyll post ... I did a fresh pull and I am missing it ... my bad.

**Comment by cestella** [comment]
I just did a clean clone locally and downloaded the patch for the pull request (https://github.com/apache/incubator-metron/pull/1.patch) and applied it (via git apply) and I'm seeing site/_posts/2015-12-09-welcome-to-jekyll.markdown

Can you confirm you see that?

**Comment by ddutta** [comment]
I see it when I apply the patch but can't figure out why my commits are not getting applied to the patch of the pull request.

**Comment by omalley** [comment]
@cestella the asf-site branch is the output of jekyll. We can have the input to jekyll either in a site directory on the master branch or create a separate branch for the jekyll source. It works either way. Unlike github, the project is required to manually run jekyll and push the output to asf-site.

**Comment by ddutta** [comment]
cestella, once this is merged I will clean up the rest.

**Comment by cestella** [comment]
Ok, sounds good.  it has my +1 then

**Comment by ddutta** [comment]
Thx!

**Comment by omalley** [comment]
I'd actually suggest creating a little news item for getting accepted to incubator.

**Comment by omalley** [comment]
Oh, you can grab the committer list from: 

http://incubator.apache.org/projects/metron.html

**Comment by cestella** [comment]
Alright, I merged this pull request.  This should close automatically.

**Comment by ddutta** [comment]
Thx!

On Thu, Dec 17, 2015 at 11:04 AM, Casey Stella <notifications@github.com>
wrote:

> Alright, I merged this pull request. This should close automatically.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-metron/pull/1#issuecomment-165549817>
> .
>



-- 
-Debo~

**Pull request merged**
