### PR TITLE
METRON-820: StellarProcessor should have a static expression cache

### PR DESCRIPTION
**Pull request by cestella**
## Contributor Comments
We recreate StellarProcessor objects all over the place which do not reuse their expression caches. This results in a significant performance regression as we are compiling the expression and then processing for every message, rather than compiling once and reusing.

As far as testing, unit tests cover this functionality quite a bit.  Also, a smoke-test with vagrant is in order (i.e. ensuring data flows through the topology) with a field transformation and a stellar enrichment set.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron (Incubating).  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root incubating-metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  bin/generate-md.sh
  mvn site:site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommened that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by ottobackwards** [comment]
1 question -> does this require any relation to the VFS cache?

**Comment by cestella** [comment]
@ottobackwards It should not.  When we start being able to handle people dropping new jars in HDFS on a *running* topology, then we will need to prune this cache.  As of now, though, a new jar in HDFS requires a topology restart, so this cache would always be fresh.

**Comment by ottobackwards** [comment]
+1 by inspection, although I'm inclined to think of a reason not to have a static cache, but instead an instance based one, I can't think of a specific case.

**Comment by mmiklavc** [comment]
Any implications to having a static cache initialized and unused if an alternate cache is passed in via the other constructors?

**Comment by cestella** [comment]
None other than the fact that we might have an empty guava cache hanging around in memory.  At the moment, nobody uses the alternative cache.

**Comment by mmiklavc** [comment]
+1 by inspection

**Pull request closed without merging**
