### PR TITLE
METRON-108 Created fast packet capture process

### PR DESCRIPTION
**Pull request by nickwallen**
Changes
-------
- Created top-level `metron-sensors` directory to contain Metron probes and sensors.
- Created fast packet capture process leveraging [DPDK](http://dpdk.org/) at `metron-sensors/packet-capture`.
- Moved Bro plugin to `metron-sensors/bro-plugin-kafka`.
- Created Ansible role to manage deployment of packet capture at `deployment/roles/packet-capture`.
- Created separate role for librdkafka installation since this is required by both Bro and Packet Capture.
- Created `deployment/vagrant/packet-capture` for launching packet capture process.  CentOS 7 is required which prevents this from being used in `deployment/vagrant/singlenode-vagrant`.

Validation
-------------
- Manually validated that the raw pcap data can be parsed by Kraken library
- Manually validated that the Kafka message key, a 64-bit unsigned being sent in network byte order, can be parsed in JVM
- Vagrant single node validated (no impact expected)
- AWS deployment validated (no impact expected)
- Manual deployment testing passed
```
cd deployment/vagrant/packet-capture
vagrant up
vagrant ssh sink
/usr/hdp/current/kafka-broker/bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic pcap
```

Q&A
-------------
#### (Q) How is this packet capture code currently integrated with the rest of Metron?

The new packet capture code is NOT installed when running the Amazon EC2, single node or multi node Vagrant deployments. I added the Vagrant setup that I have been using for testing in `deployment/vagrant/packet-capture`.  This environment can be used for test driving the packet capture process.  This creates a ‘source’ node that generates network traffic along with a ‘sink’ node that is running the packet capture process.  The 'sink' node also hosts a Kafka broker to catch the pcap.

### CODE REVIEW

**Comment by cestella** [comment]
It's unfortunate that we are unable to get this to work with singlenode vagrant.  In lieu of that, can we have at least a utility and some sample data to publish to kafka so that we can test downstream processes in singlenode vagrant?

Also, as we talked about earlier, please add a utility class and unit test showing the appropriate way to add headers to the raw data.

**Comment by nickwallen** [comment]
Yes, I am going to work on that next.  I wanted to get this chunk of code in first.

**Comment by cestella** [comment]
Got it, makes sense.  This looks great, btw.

**Comment by cestella** [comment]
So, since this touches the ansible stuff, could we please get someone else to verify that singlenode vagrant isn't broken in a too-subtle-for-me-to-detect way.  If that's ok and there's a followup PR with the testing utility, then I'm +1.

**Comment by nickwallen** [comment]
Updated description with the validation that I completed.

**Comment by dlyle65535** [comment]
Last time I checked, there was a pretty large bit of work to get EC2 working with Centos7 as well. Has that changed or is the plan to defer packet-capture until we have Centos7 deployment working?

**Comment by nickwallen** [comment]
I think that's a bridge to cross later once we refine specific deployment topologies.  The packet capture process differs from the rest of the sensors that we have to date and requires a bit of special treatment.
- This packet capture process is overkill and too cumbersome in demo/test environments.  It is really only useful for high-throughput production environments.
- Using kernel bypass technology like this means that the packet capture process does not share well with others.  No other sensors leveraging libpcap drivers can share the same network interface.
- Packet capture would most always run on a node isolated from the rest of your cluster.  The cluster could be running CentOS 6 while this runs on CentOS 7.  
- This process has to be run close to your data.  I don't foresee this running "in the cloud." It could potentially be used in a hybrid cloud deployment sending data from a secured network to the cloud.

**Comment by merrimanr** [comment]
+1 from me

**Pull request closed without merging**
