### PR TITLE
METRON-595: ES Writer uses more than one IP

### PR DESCRIPTION
**Pull request by JonathanRider**
Simple fix. Before, the client was reinitialzed for each ip, so only one was actually used. By initialing the client outside the loop, it uses all of the ip's.

### CODE REVIEW

**Comment by nickwallen** [comment]
Good catch. Thanks!  +1 by inspection, pending CI build

**Comment by JonathanRider** [comment]
Looks like the build failed for a completely unrelated test. The latest commit in master fails the build on the same test.

Should I wait until that is fixed and then merge master into my branch?

**Comment by james-sirota** [comment]
@nickwallen somehow this fix failed a profiler test. can you take a look?

**Comment by nickwallen** [comment]
Definitely seems to be some kind of sporadic failure with those integration tests.  For now, close and reopen the PR and it would likely fix it. 

I created a JIRA to track the sporadic failures.   I have yet to be able to replicate this locally. Sorry, I know these sporadic failures are annoying.  https://issues.apache.org/jira/browse/METRON-597

**Comment by ottobackwards** [comment]
I think you should >fetch apache && merge apache/master && push origin METRON-FOO

**Pull request closed without merging**
