### PR TITLE
METRON-836 Use Pycapa with Kerberos

### PR DESCRIPTION
**Pull request by nickwallen**
Changes
---------

This PR makes the necessary changes for Pycapa to work in a Kerberized environment.  
* The previous Kafka client library used by Pycapa did not support Kerberos.  Switched to another that supports Kerberos and is based on librdkafka, which is the same library used by Fastcapa and the Bro Plugin.
* Added docs on how to install and setup Pycapa for Kerberos.
* Added lots of additional docs around usage.

I tested this change on plain-vanilla Quick Dev, a kerberized-Quick Dev and also a bare-metal cluster that is using Kerberos.  

Validation
----------

The following steps can be used to validate the PR.

1. Launch the "Full Dev" environment.

1. Follow the Kerberos instructions to Kerberize the environment.  You only need to complete the following sections:
     * [Setup](https://github.com/apache/incubator-metron/blob/master/metron-deployment/vagrant/Kerberos-setup.md#setup)
     * [Create a KDC](https://github.com/apache/incubator-metron/blob/master/metron-deployment/vagrant/Kerberos-setup.md#create-a-kdc)
     * [Enable Kerberos](https://github.com/apache/incubator-metron/blob/master/metron-deployment/vagrant/Kerberos-setup.md#enable-kerberos)

1. Grant the `metron` principal access to a topic named `pcap`.

    ```
    kinit -kt /etc/security/keytabs/metron.headless.keytab metron@EXAMPLE.COM

    ${KAFKA_HOME}/bin/kafka-topics.sh \
      --zookeeper node1:2181 \
      --create \
      --topic pcap \
      --partitions 1 \
      --replication-factor 1
     
    ${KAFKA_HOME}/bin/kafka-acls.sh \
      --authorizer kafka.security.auth.SimpleAclAuthorizer \
      --authorizer-properties zookeeper.connect=node1:2181 \
      --add \
      --allow-principal User:metron \
      --topic pcap

    ${KAFKA_HOME}/bin/kafka-acls.sh \
      --authorizer kafka.security.auth.SimpleAclAuthorizer \
      --authorizer-properties zookeeper.connect=node1:2181 \
      --add \
      --allow-principal User:metron \
      --group pycapa
    ```

1. Install system dependencies including the core development tools, Python libraries and header files, and Libpcap libraries and header files.  

    ```
    yum -y install centos-release-scl
    yum -y install "@Development tools" libpcap-devel python27 python27-scldevel python27-python-virtualenv
    yum install -y cyrus-sasl cyrus-sasl-devel cyrus-sasl-gssapi
    ```

1. Install Librdkafka with SASL enabled.

    ```
    wget https://github.com/edenhill/librdkafka/archive/v0.9.4.tar.gz  -O - | tar -xz
    cd librdkafka-0.9.4/
    ./configure --prefix=/usr --enable-sasl
    make
    make install
    ```

1. Validate that Librdkafka does indeed support SASL. Run the following command and ensure that `sasl` is returned as a built-in feature.

    ```
    $ examples/rdkafka_example -X builtin.features
    builtin.features = snappy,sasl,regex
    ```
    
1. Add Librdkafka to our default load path.

    ```
    echo "/usr/lib" >> /etc/ld.so.conf.d/pycapa.conf
    ldconfig -v
    ```

1. Fetch the code from this PR. 

    ```
    cd ~
    git clone https://github.com/apache/incubator-metron
    cd incubator-metron
    git pull origin pull/524/head
    ```

1. Setup a virtual environment so that we can run Pycapa under Python 2.7.  Only needed because the base OS here is CentOS 6.

    ```
    export PY27=/opt/rh/python27/root
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PY27/usr/lib64
    
    mkdir /usr/local/pycapa
    cd /usr/local/pycapa
    $PY27/usr/bin/virtualenv pycapa-venv
    
    export VENV=/usr/local/pycapa/pycapa-venv/
    ```
    
    
1. Build and install Pycapa.

    ```
    cp -r ~/incubator-metron/metron-sensors/pycapa/ .
    cd /usr/local/pycapa/pycapa
    
    $VENV/bin/pip install -r requirements.txt
    $VENV/bin/python setup.py install
    ```

1. Use Pycapa in 'consumer-mode' which will fetch packets already landed in Kafka. This will not do anything until we inject some packets in the next step.  Leave this running in the current shell.

    ```
    $VENV/bin/pycapa --consumer \
      --kafka-broker node1:6667 \
      --kafka-topic pcap \
      --pretty-print 1 \
      -X security.protocol=SASL_PLAINTEXT \
      -X sasl.kerberos.keytab=/etc/security/keytabs/metron.headless.keytab \
      -X sasl.kerberos.principal=metron@EXAMPLE.COM \
      -X group.id=pycapa
    ```

1. Open a second shell and use Pycapa in 'consumer mode' to capture a few packets and throw those into Kafka.

    ```
    export PY27=/opt/rh/python27/root
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PY27/usr/lib64
    export VENV=/usr/local/pycapa/pycapa-venv/
    
    $VENV/bin/pycapa --producer \
      --interface eth1 \
      --kafka-broker node1:6667 \
      --kafka-topic pcap \
      --pretty-print 1 \
      --max-packets 5 \
      -X security.protocol=SASL_PLAINTEXT \
      -X sasl.kerberos.keytab=/etc/security/keytabs/metron.headless.keytab \
      -X sasl.kerberos.principal=metron@EXAMPLE.COM 
    ```
    
1. In the original shell, where Pycapa was running in 'consumer-mode' you should see the packets.  It should look-like the following.

    ```
    ....
    
    Packet: count=1 date=2017-04-19 21:07:08.345337 topic=pcap
    08 00 27 f6 b0 07 52 54 00 12 35 02 08 00 45 00
    00 4c 1e 04 00 00 40 06 44 98 0a 00 02 02 0a 00
    02 0f db 13 00 16 12 91 0b b7 b1 79 ee fe 50 18
    ff ff 18 3d 00 00 7b 55 37 93 46 b8 8f fe 98 e0
    10 f3 42 53 06 51 6d 8b 4c d1 45 07 ea 51 57 58
    6b d2 67 74 75 d7 fd 1d e2 0e
    Packet: count=2 date=2017-04-19 21:07:08.345884 topic=pcap
    52 54 00 12 35 02 08 00 27 f6 b0 07 08 00 45 10
    00 b4 09 68 40 00 40 06 18 bc 0a 00 02 0f 0a 00
    02 02 00 16 db 13 b1 79 ee fe 12 91 0b db 50 18
    59 80 18 b7 00 00 d3 b3 9b fb 2b 4a 70 57 d6 49
    d6 ab 7c 26 7d cd 87 9b 41 27 50 f4 94 45 3f 0c
    58 c3 31 24 79 9a 0a 96 9a df d3 17 75 43 76 5d
    ed 07 74 f1 b7 bb aa 0c 38 72 0a 58 e4 2d a9 02
    b6 e8 83 e7 3b 95 04 78 30 d4 a5 de 54 94 be 2d
    10 08 08 b1 27 e1 ba 9e b7 74 b4 12 a5 3a 5e de
    39 fb 5b 97 c7 07 4a 10 4f e9 ba 59 42 1d 65 c3
    0d 04 22 30 62 ce 56 d1 20 06 0f 6b 73 09 82 c9
    cb 4c 6c 7e 3f 50 ac 7c 26 83 0a 47 d8 ef 44 39
    f7 b6
    Packet: count=3 date=2017-04-19 21:07:08.346004 topic=pcap
    52 54 00 12 35 02 08 00 27 f6 b0 07 08 00 45 10
    00 4c 09 69 40 00 40 06 19 23 0a 00 02 0f 0a 00
    02 02 00 16 db 13 b1 79 ef 8a 12 91 0b db 50 18
    59 80 18 4f 00 00 37 f4 72 54 28 a5 14 ed 5a 4a
    1f b0 f0 7d 0d be 94 a4 b0 54 a3 2f d7 3a 00 41
    59 fe 13 28 18 88 5a 84 b9 44
    Packet: count=4 date=2017-04-19 21:07:08.346051 topic=pcap
    08 00 27 f6 b0 07 52 54 00 12 35 02 08 00 45 00
    00 28 1e 05 00 00 40 06 44 bb 0a 00 02 02 0a 00
    02 0f db 13 00 16 12 91 0b db b1 79 ef 8a 50 10
    ff ff fd 29 00 00 00 00 00 00 00 00
    Packet: count=5 date=2017-04-19 21:07:08.346288 topic=pcap
    08 00 27 f6 b0 07 52 54 00 12 35 02 08 00 45 00
    00 28 1e 06 00 00 40 06 44 ba 0a 00 02 02 0a 00
    02 0f db 13 00 16 12 91 0b db b1 79 ef ae 50 10
    ff ff fd 05 00 00 00 00 00 00 00 00
    ```

## Pull Request Checklist

- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root incubating-metron folder via:
- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

### CODE REVIEW

**Comment by nickwallen** [comment]
Would love to get this reviewed.

**Comment by nickwallen** [comment]
Based on feedback, I have added a series of specific steps to validate this change.  That should help simplify validation.  I should have included that on the first pass.

**Comment by nickwallen** [comment]
I updated the validation instructions to setup a Kerberized environment and then validate Pycapa against that environment.

**Comment by nickwallen** [comment]
Calling all reviewers.  Would love to get this closed out and off my plate.  Thanks!

**Comment by JonZeolla** [comment]
Sorry, I started reviewing this but it dropped off when @merrimanr mentioned on the dev list that he was also reviewing it.  If there's no progress in the next day or two, I may be able to take another look.  I did follow your initial instructions and it looked good to me, I just haven't followed your latest instructions.

**Comment by nickwallen** [comment]
Hey, the more reviewers the better.  No harm in that.

**Comment by merrimanr** [comment]
I was able to get this to work by performing one extra step.  The PR description did not include the Kafka ACL command to permission the topic, only the "pycapa" group.  After I did this, I was able to verify data with the pycapa --consumer command.  The topic ACL command is included in the Pycapa README so I think simply adding the ACL command for the group is all that's needed.

I did notice that running the pycapa --producer command causes a Kafka service ticket to be cached.  Since we're passing in the metron principal and keytab I would expect that ticket to be in the cache instead.  While it's unexpected it did not cause any errors.

One last minor documentation issue:  this PR description includes steps to install Python 2.7 but nowhere is that mentioned in the README.  I know it's only needed because full dev is centos 6 but it might be helpful to at least call out Python 2.7 as a prereq.  Maybe it's assumed the user knows that but it tripped me up when I was initially trying to spin this up and that wasn't included in the PR description.

The only issue above I feel is necessary to address would adding the extra Kafka ACL command for the group to the README.  Pending that change, +1.

**Comment by nickwallen** [comment]
> One last minor documentation issue: this PR description includes steps to install Python 2.7 but nowhere is that mentioned in the README.

The latest README now mentions Python 2.7.

> The only issue above I feel is necessary to address would adding the extra Kafka ACL command for the group to the README

I updated the README and the PR description to set the ACL on the topic and on the group.

Yay!

**Comment by merrimanr** [comment]
Looks good!  +1

**Pull request closed without merging**
