### PR TITLE
METRON-944: markdown table causes infinite hanging in site-book's doxia-module-markdown

### PR DESCRIPTION
**Pull request by justinleet**
## Contributor Comments
Hangs less. Still not performant (takes ~30 seconds), but at least the tables aren't trash.  Stripped out as many columns as reasonable, split into different tables, etc.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by justinleet** [comment]
Just spin up the site-book and make sure it a) completes (~30s) and b) doesn't look like hot garbage in the site-book

**Comment by mattf-horton** [comment]
@justinleet , there's also a problem on this page with code blocks after numeric list items. They need to be indented so they don't cause restarts of the numbering. I've submitted PR#5 to this fork to fix them. You may merge without attribution.

I've regenerated, and confirmed that while site takes longer than it used to, it works and returns within a reasonable amount of time. Good work, Justin!

**Comment by ottobackwards** [comment]
+1 - generated site and opened in browser, clicked around.  Thanks for jumping on this

**Comment by justinleet** [comment]
@mattf-horton Thanks for catching that.  Merged it in.

**Comment by mattf-horton** [comment]
+1 : confirmed current state same as one I tested.  Thanks, @justinleet !

**Pull request closed without merging**
