### PR TITLE
METRON-541: Set log levels for Metron components

### PR DESCRIPTION
**Pull request by merrimanr**
This PR accomplishes primarily 2 things:  sets the log level for all components (and their dependencies) to ERROR and suppresses ERROR log statements in tests for cases where an exception is expected.  Ideally a combination of this PR and #344 will make the output logs in Travis much cleaner.

The approach for setting the log level is to exclude all transitive SJF4J bindings and instead declare the log4j binding in the metron-platform and metron-analytics poms (would top level be better?).  There is some code that uses log4j instead SLF4J so this binding seemed appropriate.  Now there are no more SLF4J warnings and the log level for every component can be configured in test/resources/log4j.properties.  It is currently set to ERROR by default but do we want to add different log files for different profiles (dev, travis, prod, etc)?

The approach for suppressing expected ERROR log messages is to temporarily change the log level to SEVERE/FATAL during a test that generates an ERROR message and change it back right after the test (or line within the test) has executed.  A couple of methods to programmatically change the log level at runtime was added to the UnitTestHelper class.  

There were a few test cases where an exception was incorrectly thrown so I fixed those (BulkMessageWriterBoltTest.java and ParserBoltTest.java).

There are a lot of different ways to do logging so I'm expecting the community will have opinions on what the right approach is for us.  I have tested this with unit/integration tests and will test with vagrant once we get closer to a consensus.

### CODE REVIEW

**Comment by cestella** [comment]
Did you check this on vagrant?  I seem to remember there being some drama when I tried to remove the slf4j dependencies around some of the data management functions.  Specifically, calling the `flatfile_loader.sh`.

**Comment by mmiklavc** [comment]
@merrimanr Love this effort. We just went through something similar in getting the apache curator versions lined up for the Storm upgrade support ticket. Thinking more about it, I'm not sure we need to explicitly exclude all of these dependencies. Can we try just an explicit declaration at the global level?  Per "Dependency mediation" from the Maven docs:

> You can always guarantee a version by declaring it explicitly in your project's POM. Note that if two dependency versions are at the same depth in the dependency tree, until Maven 2.0.8 it was not defined which one would win, **but since Maven 2.0.9 it's the order in the declaration that counts: the first declaration wins**. 

I *think* our own explicit declarations should supersede the transitive dependencies, which should clean up our poms quite a bit if I'm right about that.

https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies

**Comment by merrimanr** [comment]
@cestella I don't think that will be an issue since the binding is now coming from the metron-platform pom but I will definitely test it in vagrant after we get some feedback.

**Comment by ottobackwards** [comment]
Ok - you beat me in.  I think my PR should be dependent on this.  When this goes in, I'll sync up with master etc etc

**Comment by merrimanr** [comment]
@mmiklavc Good question.  We definitely need to exclude the SLF4J bindings that we don't use.  The most common one is the Log4J2 binding that Storm brings along ("org.apache.logging.log4j:log4j-slf4j-impl").  

It could be argued that we don't need to exclude the binding we are using ("org.slf4j:slf4j-api") and control the version through dependency management as you suggest.  The downside I see there though is that if we ever did want to change the logging implementation we would have to go through all the poms and exclude that binding (what's already been done here).  As it stands, changing the logging implementation is as simple as changing the binding in the metron-platform/analytics pom files and adding logging configuration files.

**Comment by merrimanr** [comment]
Resolved a merge conflict with SnortParserTest and changed Travis configuration to not run mvn install (since we're already doing it as part of our tests).  Check out those logs!  The stack traces should be gone after #344.

**Comment by mmiklavc** [comment]
I'll miss those verbose logs. +1 pending the vagrant checks.

**Pull request closed without merging**
