### PR TITLE
METRON-357: Create Ambari Service Definition for Kibana

### PR DESCRIPTION
**Pull request by dlyle65535**
First iteration of the Kibana Service which is required to deploy Metron via Ambari.

Steps to test:

On a running Ambari-managed cluster:

copy metron-deployment/packaging/ambari/src/main/resources/stacks/HDP/2.4/services/KIBANA to /var/lib/ambari-server/resources/stacks/STACK-NAME/STACK-VERSION/services/KIBANA

copy metron-deployment/packaging/ambari/src/main/resources/common-services/KIBANA to /var/lib/ambari-server/resources/common-services/KIBANA

restart ambari-server

use the Add Service wizard to add Kibana to your cluster.

Note: STACK-NAME and STACK-VERSION need to be substituted for your environment. For example, if testing on HDP 2.4, STACK-NAME = HDP and STACK-VERSION = 2.4

### CODE REVIEW

**Comment by dlyle65535** [comment]
Bump?

**Comment by cestella** [comment]
Sorry Dave!  I was sleeping on the job.  +1 by inspection, this looks good

**Comment by nickwallen** [comment]
Looks very cool. I am trying to test this.  In your instructions you have a placeholder called STACK-VERSION.  

When I look at my install of Ambari, I see a clusterf* of possible STACK-VERSIONs.  How can I tell which STACK-VERSION I should be using?  Can I find that in the Ambari UI somehow?

```
[root@node1 ambari-server]# ls -l /var/lib/ambari-server/resources/stacks/HDP/
total 32
drwxr-xr-x. 4 root root 4096 May  2 16:55 2.0
drwxr-xr-x. 6 root root 4096 May  2 16:55 2.0.6
drwxr-xr-x. 4 root root 4096 May  2 16:55 2.0.6.GlusterFS
drwxr-xr-x. 5 root root 4096 May  2 16:55 2.1
drwxr-xr-x. 5 root root 4096 May  2 16:55 2.1.GlusterFS
drwxr-xr-x. 6 root root 4096 May  2 16:55 2.2
drwxr-xr-x. 5 root root 4096 May  2 16:55 2.3
drwxr-xr-x. 5 root root 4096 May  2 16:55 2.3.GlusterFS
```

**Comment by dlyle65535** [comment]
I don't have an Ambari running right now, but it's somewhere under Stacks and Versions (then Stacks under that iirc).

Looks like yours will be 2.3.

**Comment by nickwallen** [comment]
Everything went smoothly with the Kibana installation.  Love the guided installation process.  

I did get a warning when it tried to start Kibana and failed to.  I get the same error when trying to start Kibana through Ambari after the installation process.  

I can login to the host and successfully start Kibana with a `service kibana start`.  I am assuming its an issue with the Ambari configuration, not the Kibana configuration that Ambari laid down.

```
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/common-services/KIBANA/4.5.1/package/scripts/kibana_master.py", line 86, in <module>
    Kibana().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 216, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/common-services/KIBANA/4.5.1/package/scripts/kibana_master.py", line 63, in start
    self.configure(env)
  File "/var/lib/ambari-agent/cache/common-services/KIBANA/4.5.1/package/scripts/kibana_master.py", line 50, in configure
    kibana()
  File "/var/lib/ambari-agent/cache/common-services/KIBANA/4.5.1/package/scripts/kibana.py", line 42, in kibana
    print "Master env: ""{}/kibana.yml".format(params.conf_dir)
ValueError: zero length field name in format
```

**Comment by nickwallen** [comment]
I was able stop Kibana from the command-line and after a minute or so Ambari reported Kibana as stopped (red) in the UI.  That's good stuff.

**Comment by dlyle65535** [comment]
I suspect this requires Ambari 2.4 to work, there seems to be an issue with the params getting filled in otherwise. I'll dig into it a bit.

**Comment by nickwallen** [comment]
I can spin-up a cluster with the latest from master and try it out there, if you like.  If it is just an issue with my environment, and we're not aiming for backwards-compat, then maybe that makes sense.

**Comment by dlyle65535** [comment]
I'm not really sure what the right answer is. I've been testing with 2.4 (that's the targeted version), but I would expect it to run on 2.3. Our current quick dev is actually 2.1.2.1, so that could be an issue.

**Comment by nickwallen** [comment]
Yes, my testing was with quick-dev and 2.1.2.1

**Comment by dlyle65535** [comment]
I think I'll fire up a 2.3 and see if the problem occurs there as well.

**Comment by dlyle65535** [comment]
I ran this up on 2.2 and 2.4 and both ran fine. There must be some sort of issue with 2.1.2.1.

**Comment by james-sirota** [comment]
+1

**Pull request closed without merging**
