### PR TITLE
METRON-69 EC2 Volume Enhancements

### PR DESCRIPTION
**Pull request by nickwallen**
### Changes
- The EC2 volume sizes are now configurable
- The root volume is only expanded if needed.

### Validation
- [x] Positive and negative tests on live EC2 cluster.
- [x] License Check
- [x] Integration Tests

### CODE REVIEW

**Comment by nickwallen** [comment]
@dlyle65535 - Please take a gander

**Comment by dlyle65535** [comment]
Overall looks good. I'll run it up. Originally, I only intended this to run once at first provisioning. You may want to consider enforcing that. I wouldn't move a partition end on a system after initial buildout.

**Comment by nickwallen** [comment]
Yes, this is a gap, but one that did already exist.  At the very least this change is not making things worse.

Personally I would not be too concerned about this. if conditions ever exist for the 'expand-volume' logic to fire when it shouldn't then there are likely larger problems in the environment.  The kind of 'larger' problems that might cause someone to just shoot the node in the head and start over anyways.  I could be wrong though.

**Comment by dlyle65535** [comment]
I think the gap was that since we still have some work to do on idempoentence in the scripts, I mistakenly believed that no one would run these twice and expect to be happy with the result. It that holds (and potentially is documented somewhere) I'm good.

**Comment by nickwallen** [comment]
Are you saying that we should not merge this PR until everything is completely idempotent?  Totally open to a -1 if you think there is a better way that we should do this.

**Comment by dlyle65535** [comment]
No, not at all. Just don't want to introduce more places where it breaks.

**Comment by dlyle65535** [comment]
+1 as is. Thanks!

**Pull request closed without merging**
