### PR TITLE
[METRON-12] Replace all instances of 'OpenSoc' with 'Metron'

### PR DESCRIPTION
**Pull request by ehashman**
Caveats:

- I left all of the `pom.xml.versionsBackup`s alone
- I successfully built the code but don't have a machine or cluster powerful enough to test it on

Here are all the remaining references to OpenSOC left in the project, excluding the backup POMs:

```
$ git grep -i opensoc | grep -v versionsBackup
metron-streaming/Metron-Common/pom.xml:			<url>https://raw.github.com/opensoc/kraken/mvn-repo</url>
metron-streaming/Metron-DataServices/src/main/java/com/apache/metron/pcapservice/PcapGetterHBaseImpl.java:   * @see com.cisco.opensoc.hbase.client.IPcapGetter#getPcaps(java.util.List,
metron-streaming/Metron-DataServices/src/main/java/com/apache/metron/pcapservice/PcapGetterHBaseImpl.java:   * @see com.cisco.opensoc.hbase.client.IPcapGetter#getPcaps(java.lang.String, long,
metron-streaming/Metron-DataServices/src/main/java/com/apache/metron/pcapservice/PcapGetterHBaseImpl.java:   * @see com.cisco.opensoc.hbase.client.IPcapGetter#getPcaps(java.util.List)
metron-streaming/Metron-DataServices/src/main/java/com/apache/metron/pcapservice/PcapGetterHBaseImpl.java:   * @see com.cisco.opensoc.hbase.client.IPcapGetter#getPcaps(java.lang.String)
metron-streaming/Metron-DataServices/src/main/java/com/apache/metron/pcapservice/PcapReceiverImplRestEasy.java:	   * com.cisco.opensoc.hbase.client.IPcapReceiver#getPcapsByIdentifiers(java.lang
metron-streaming/Metron-DataServices/src/main/java/com/apache/metron/pcapservice/PcapScannerHBaseImpl.java:   * @see com.cisco.opensoc.hbase.client.IPcapScanner#getPcaps(java.lang.String,
metron-streaming/Metron-DataServices/src/main/java/com/apache/metron/pcapservice/PcapScannerHBaseImpl.java:   * @see com.cisco.opensoc.hbase.client.IPcapScanner#getPcaps(java.lang.String,
metron-streaming/Metron-Pcap_Service/src/main/java/com/apache/metron/pcapservice/PcapGetterHBaseImpl.java:   * @see com.cisco.opensoc.hbase.client.IPcapGetter#getPcaps(java.util.List,
metron-streaming/Metron-Pcap_Service/src/main/java/com/apache/metron/pcapservice/PcapGetterHBaseImpl.java:   * @see com.cisco.opensoc.hbase.client.IPcapGetter#getPcaps(java.lang.String, long,
metron-streaming/Metron-Pcap_Service/src/main/java/com/apache/metron/pcapservice/PcapGetterHBaseImpl.java:   * @see com.cisco.opensoc.hbase.client.IPcapGetter#getPcaps(java.util.List)
metron-streaming/Metron-Pcap_Service/src/main/java/com/apache/metron/pcapservice/PcapGetterHBaseImpl.java:   * @see com.cisco.opensoc.hbase.client.IPcapGetter#getPcaps(java.lang.String)
metron-streaming/Metron-Pcap_Service/src/main/java/com/apache/metron/pcapservice/PcapReceiverImplRestEasy.java:	   * com.cisco.opensoc.hbase.client.IPcapReceiver#getPcapsByIdentifiers(java.lang
metron-streaming/Metron-Pcap_Service/src/main/java/com/apache/metron/pcapservice/PcapScannerHBaseImpl.java:   * @see com.cisco.opensoc.hbase.client.IPcapScanner#getPcaps(java.lang.String,
metron-streaming/Metron-Pcap_Service/src/main/java/com/apache/metron/pcapservice/PcapScannerHBaseImpl.java:   * @see com.cisco.opensoc.hbase.client.IPcapScanner#getPcaps(java.lang.String,
site/_docs/index.md:Back in December 2015, we created Metron files as part of the transition of the OpenSOC project from Cisco. 
site/develop/bylaws.md:the Apache Board in December 2015 when Metron moved out of Cisco's OpenSOC  
site/talks/index.md:* Cisco OpenSOC with Bro [slides](http://www.slideshare.net/JamesSirota/cisco-opensoc)
site/talks/index.md:    <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/JamesSirota/cisco-opensoc" title="Cisco OpenSOC" target="_blank">Cisco OpenSOC Talk </a> </strong> by <strong> <a href="https://www.youtube.com/watch?v=UKgjd4ttg8o" target="_blank">Kurt Grutzmacher</a> </strong></div>
site/talks/index.md:* Cisco OpenSOC talk
site/talks/index.md:    <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/JamesSirota/cisco-opensoc" title="Cisco OpenSOC" target="_blank">Cisco OpenSOC </a> </strong> from <strong> <a href="//www.slideshare.net/JamesSirota" target="_blank">James Sirota</a> </strong> </div>
```

### CODE REVIEW

**Comment by sirsean** [comment]
I almost hate to say this but the packages have been named `com.apache.metron...` and I think they ought to be `org.apache.metron...` (on account of Apache's domain name).

**Comment by charlesporter** [comment]
it should be **org.apache.metron**  rather than **com.apache.metron** , right?

**Comment by ehashman** [comment]
Oh noooooooo I totally missed that >.< I will fix that later today.

**Comment by sirsean** [comment]
It looks like everything is moved to the right places. I can't find any code changes that aren't renames. It still builds and the tests all pass. The topologies run in local mode the same way they used to.

LGTM +2

**Comment by reaperhulk** [comment]
Checked out this branch and confirmed as well :+1:

**Pull request merged**
