### PR TITLE
METRON-117 Deployment Report Created for All Deployments

### PR DESCRIPTION
**Pull request by nickwallen**
### [METRON-117](https://issues.apache.org/jira/browse/METRON-117)

* The deployment report was only produced for AWS-based deployments.  Now all deployments, including Vagrant and Bare Metal, will produce the same deployment report. 
* Enhanced the report to show the Zookeeper and Kafka URLs.
* Example of report produced for Vagrant based deployment.
    ```
    TASK [deployment-report : Sanity check Metron web] *****************************
    ok: [node1 -> localhost]

    TASK [deployment-report : Sanity check Ambari web] *****************************
    ok: [node1 -> localhost]

    TASK [deployment-report : Known hosts groups] **********************************
    ok: [node1] => {
        "groups": {
            "all": [
                "localhost",
                "node1"
            ],
            "ambari_master": [
                "node1"
            ],
            "ambari_slave": [
                "node1"
            ],
            "enrichment": [
                "node1"
            ],
            "metron": [
                "node1"
            ],
            "metron_hbase_tables": [
                "node1"
            ],
            "metron_kafka_topics": [
                "node1"
            ],
            "mysql": [
                "node1"
            ],
            "pcap_server": [
                "node1"
            ],
            "search": [
                "node1"
            ],
            "sensors": [
                "node1"
            ],
            "ungrouped": [
                "localhost"
            ],
            "web": [
                "node1"
            ]
        }
    }

    TASK [deployment-report : set_fact] ********************************************
    ok: [node1]

    TASK [deployment-report : debug] ***********************************************
    ok: [node1] => {
        "Success": [
            "Apache Metron deployed successfully",
            "   Metron          @ http://node1:5000",
            "   Ambari          @ http://node1:8080",
            "   Sensor Status   @ http://node1:2812",
            "   Topology Status @ http://node1:2812",
            "   Zookeeper       @ node1:2181",
            "   Kafka           @ node1:6667",
            "For additional information, see https://metron.incubator.apache.org/'"
        ]
    }
    ```

### CODE REVIEW

**Comment by dlyle65535** [comment]
I'm still not comfortable in general on grouping unrelated JIRAs into a single PR. Any reason this wasn't 2 PRs?

Also, are the invalid/error topics being created?

**Comment by nickwallen** [comment]
Removed all changes related to METRON-279.

**Comment by dlyle65535** [comment]
+1, looks good. Thanks!

**Comment by cestella** [comment]
+1, by inspection

**Pull request closed without merging**
