### PR TITLE
METRON-384 Allow elasticsearch to bind to loopback addresses

### PR DESCRIPTION
**Pull request by 2xyo**
This PR addresses https://issues.apache.org/jira/browse/METRON-384

### CODE REVIEW

**Comment by dlyle65535** [comment]
I like what you did here, but could you expose it as a parameter and default it to ipv4 instead?

**Comment by 2xyo** [comment]
Thanks @dlyle65535  for the feedback.

Would you prefer a configuration like this?

Old `full-dev-platform/group_vars/all`:
```
elasticsearch_network_interface: eth0
```

New  `full-dev-platform/group_vars/all`:
```
elasticsearch_network_interface:
- eth0
- local
```

If yes, I dont' know how to implement a loop with the `lineinfile` module :/

Could you also elaborate the "ipv4 instead"? (As the result is already ipv4 only "`network.host: ["_eth0:ipv4_","_local:ipv4_"]`" )

**Comment by dlyle65535** [comment]
Sorry, I meant eth0 only. I'd try adding network_host: _{{
    elasticsearch_network_interface  }}:ipv4_' } to the role's defaults and then you can override it in the group vars to whatever you'd like rather than mess with looping.

**Comment by 2xyo** [comment]
So, you would recommend something like this:

New  `elasticsearch.yml`:
```
  - { regexp: '^# *network\.host:', line: 'network.host: {{elasticsearch_network_interface  }}' }
```

New  `full-dev-platform/group_vars/all`, `multinode-vagrant/group_vars/all`:
```
elasticsearch_network_interface: _eth1:ipv4_
```
And new  `metron_example/group_vars/all `, `amazon-ec2/conf/defaults.yml`:
```
elasticsearch_network_interface: _eth0:ipv4_
```

But, in this case, elasticsearch will not listening to localhost by default (and that's why I opened this issue). IMHO, the default value should be instead:
```
elasticsearch_network_interface: ["_eth1:ipv4_","_local:ipv4_"]
```

**Comment by dlyle65535** [comment]
I'm +1 on this, thanks for the contribution.

**Comment by dlyle65535** [comment]
Could you post an email address to use for the commit? Thanks!

**Comment by 2xyo** [comment]
Thanks! Here is my email: yohann@lepage.info

**Pull request closed without merging**
