### PR TITLE
METRON-818: Ambari elasticsearch.properties template is missing topology.worker.childopts

### PR DESCRIPTION
**Pull request by justinleet**
## Contributor Comments
Adding the empty config to the Ambari elasticsearch.properties template.

To test, spin up in a dev environment.  Indexing topology should produce results instead of an error in the logs now.

I'm still running this up in dev, but wanted to let people see what's going on. will update shortly.

As a workaround, just add this line to a running Ambari instance and restart indexing in Ambari to push the configs.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron (Incubating).  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root incubating-metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- ~Have you written or updated unit tests and or integration tests to verify your changes?~
- ~If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?~
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- ~Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes~
#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommened that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by mmiklavc** [comment]
+1 by inspection. Same thing we're doing with enrichment and must have missed in the indexing configs. Do we need to add this for Solr?

**Comment by justinleet** [comment]
@mmiklavc We probably should edit the Solr config.  That isn't carried through Ambari, so we don't have the same concern as here.  However, it does look like `storm.auto.credentials=[]` got added to solr.properties and I thought it wasn't necessary there.  Can we just drop that config and add the 'topology.worker.childopts='?

Should I just go ahead and make that chance and add it to this PR?  And if I do, do we have any testing plan for Solr or are we just making best effort fixes?

**Comment by cestella** [comment]
I'd argue for a best effort fix for solr and that you should just drop that config and add topology.worker.childopts.

**Comment by cestella** [comment]
Also +1 by inspection

**Comment by JonZeolla** [comment]
Spinning this up now.

**Comment by justinleet** [comment]
Full dev spun up and ran fine, and I see items showing up in ES and HDFS

**Comment by justinleet** [comment]
@JonZeolla did you have any issues spinning this up?

**Comment by JonZeolla** [comment]
I ran into a few issues related to my environment (surprise - if you don't have a network it's hard to do much) but I did end up getting full-dev up and functional once that was sorted out.  +1

**Comment by justinleet** [comment]
Thanks for running it up and verifying it.

**Pull request closed without merging**
