### PR TITLE
METRON-715: Removed MySQL from Enrichment Diagram

### PR DESCRIPTION
**Pull request by simonellistonball**

### CODE REVIEW

**Comment by james-sirota** [comment]
+1 by inspection. thanks for catching this, simon

**Comment by JonZeolla** [comment]
Please rename the PR to "Metron-715: Enrichment Diagram still includes MySQL, which is no longer used".  Also +1 (non-binding) by inspection

**Comment by ottobackwards** [comment]
Please rename the PR to start with "METRON-715".  Then we can land this

**Comment by cestella** [comment]
+1 by inspection, thanks for the contribution, Simon :)

**Pull request closed without merging**
