### PR TITLE
METRON-595: ES Writer uses more than one IP

### PR DESCRIPTION
**Pull request by JonathanRider**
Resubmitting pull request due to sporadic test failure as per comments on the last pull request.

Simple fix. Before, the client was reinitialized for each ip, so only one was actually used. By initialing the client outside the loop, it uses all of the ip's.

### CODE REVIEW

**Comment by dlyle65535** [comment]
Thanks for this change, @JonathanRider - can you tell me how you tested it?

**Comment by JonathanRider** [comment]
Just realized we had some custom code since we couldn't get the List object working for feeding in multiple IP's. So I added in the code so you can just have a comma separated list of IP's. 

We have a dev cluster that has 3 master nodes, but I only gave the writer 2 ip addresses. I sent data through, then stopped the elasticsearch service on that machine. Sent data through and it works (previously this would give a NoNodeAvailable exception). I then started ES back up on that server, and shut down the ES Service on the other server and sent data through again and it also works.

**Comment by JonathanRider** [comment]
Is there anything else I need to do in order to get this merged in, @dlyle65535 ?

**Comment by dlyle65535** [comment]
Could you give it a run up on Quick Dev using your patch rebased on master?

**Comment by JonathanRider** [comment]
Is quickdev working currently? I just spun it up and tried to start up a parser topology but get an error. Looking at it, it seems like the error seen here: https://community.hortonworks.com/questions/68798/metron-enrichment-fail-to-start-with-ambari-instal.html

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/storm/Config
	at org.apache.metron.parsers.topology.ParserTopologyCLI$ParserOptions.<init>(ParserTopologyCLI.java:199)
	at org.apache.metron.parsers.topology.ParserTopologyCLI$ParserOptions.<clinit>(ParserTopologyCLI.java:47)
	at org.apache.metron.parsers.topology.ParserTopologyCLI.main(ParserTopologyCLI.java:266)
Caused by: java.lang.ClassNotFoundException: org.apache.storm.Config
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

**Comment by ottobackwards** [comment]
quick dev is working - i spun one up this morning from a new branch off of master

**Comment by JonathanRider** [comment]
And you can start a topolgy in it? This is the command I'm running:
/usr/metron/0.3.0/bin/start_parser_topology.sh -z node1:2181 -k node1:6667 -s bro

And storm version gives 0.10.0.2.3.4.7-4
And the HDP stack in ambari says: HDP-2.3.4.7-4

Can you confirm that these match yours?

**Comment by JonathanRider** [comment]
Just ran it on quickdev where I set the es.host in the global json file to "node2,node1" where node2 doesn't exist as it is a single node vagrant.

Using my patch, it writes to ES without a problem as it fails to use node2, so it switches to node1.

I then compiled master and did the same thing and received this error since node2 doesn't exist and it fails to use the second host.:
2016-12-01 21:41:18.942 o.a.m.w.BulkWriterComponent [ERROR] Failing 5 tuples
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{10.120.164.190}{node2/10.120.164.190:9300}]

**Comment by JonathanRider** [comment]
@dlyle65535 is there anything specific that you wanted me to test on quickdev that I haven't already done?

**Comment by dlyle65535** [comment]
Nope, looks like you did a test run with changes and @ottobackwards did the clean one I was going to do, so I'm +1.
Thanks!

**Comment by ottobackwards** [comment]
@dlyle65535 I did not test, I was answering the question of if quick-dev works at all

**Comment by dlyle65535** [comment]
Oh, thanks for that. Let me run it up really quickly then. Totally mis-read you, @ottobackwards.

**Comment by dlyle65535** [comment]
This looks good to me, @JonathanRider - do you want me to use the email on your profile for the commit?

**Comment by JonathanRider** [comment]
Yep. Thanks!

**Pull request closed without merging**
