### PR TITLE
METRON-319: Automate RPM Builds in Maven

### PR DESCRIPTION
**Pull request by justinleet**
Creates a Maven build for building the RPMs directly from Maven.

### CODE REVIEW

**Comment by justinleet** [comment]
To test, ensure Docker is installed and ready for builds
Ensure the metron-platform is at least packaged (no code is added to metron-platform, so skipping the tests should be acceptable).
From the main directory:
`mvn clean package -DskipTests`

Afterwards, navigate to metron-deployment and run:
`mvn clean package`

A docker image should be built if it's the first run, then run with a script to create the RPMs.  They will be copied to the standard target folder.

On followon runs, the Docker container should mostly be skipped and will create the same RPMs.

After the run, RPMs should be available in /target/RPMS/noarch.

**Comment by dlyle65535** [comment]
Overall, looks great- one small thing:

Testing fails on docker-machine and boot2docker because of permission issues on docker volumes.
Testing passes on Docker for Mac.

You may want to call that out in the README. Otherwise, I'm +1, good job!

**Comment by justinleet** [comment]
Good catch. I've added a note to the README calling out the Docker Toolbox vs. Docker for Mac issue, and updated this PR.

**Comment by nickwallen** [comment]
+1 This is super nice.  I am using Docker for Mac and was able to successfully build all of the RPMs.  I was then able to successfully install all of the RPMs on a CentOS 6 box.

**Comment by anandsubbu** [comment]
Hello @nickwallen, can you tell me the version of CentOS 6 that you attempted? 

I was able to build the RPMs fine, but was unable to install them on a CentOS 6.8 openstack VM. 
`[root@metron-multi-anand-13 metron-rpms]# rpm -ivh *`
`warning: selinux-policy-targeted-3.13.1-23.el7_1.13.noarch.rpm: Header V4 DSA/SHA1 Signature, key ID 192a7d7d: NOKEY`
`error: Failed dependencies:`
`	policycoreutils >= 2.1.14-74 is needed by selinux-policy-targeted-3.13.1-23.el7_1.13.noarch`
`	selinux-policy = 3.13.1-23.el7_1.13 is needed by selinux-policy-targeted-3.13.1-23.el7_1.13.noarch`

Here are my system details:
`[root@metron-multi-anand-13 metron-rpms]# uname -a`
`Linux metron-multi-anand-13 2.6.32-504.1.3.el6.x86_64 #1 SMP Tue Nov 11 17:57:25 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`
`[root@metron-multi-anand-13 metron-rpms]# cat /etc/redhat-release`
`CentOS release 6.8 (Final)`

Note that I did `yum update` before attempting to install the RPMs. Am I missing something? 

Thanks,
Anand

**Pull request closed without merging**
