### PR TITLE
METRON-912: Metron vagrant setup steps no longer work

### PR DESCRIPTION
**Pull request by JonZeolla**
## Contributor Comments
If you run the old steps you will install multiple inaccurate versions of tools:
1.  Maven `3.5.0` will be installed, but we specifically request people use `3.3.9`.
1.  Ansible latest is now `2.3.0.0`, and we request `2.2.2.0`.  This has been a specific point of issue, although I have not tested `2.3.0.0`.
1.  `brew cask install docker` does not install the components which we expect to exist, specifically the docker daemon.  I have only ever found the required components to be available when installing via their [install steps](https://docs.docker.com/engine/installation/).  Happy to be proven wrong on this one, but when I checked around with others, it seems everybody that I've spoken with actually follow these steps anyway.

I also purposefully removed some versioning granularity based off of experience, in hopes that this will continue to be accurate for a longer period of time.  For instance, I'm fairly certain any version of Python 2.7.x works just fine with Metron, and that the Vagrant and Virtualbox versions (as long as they are relatively new) are not an issue.

Note I removed the link to use the Ansible-provided instructions to install via brew because they do not support installing anything other than the latest (currently 2.3.0.0), as documented [here](https://github.com/caskroom/homebrew-cask/issues/25305) and [here](http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-pip).

## Testing
Uninstall the prereqs from your machine and install using the steps provided.  Spin up full-dev, quick-dev, etc. using the versions provided in the above steps.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [X] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  bin/generate-md.sh
  mvn site:site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by JonZeolla** [comment]
Bump - this should be an easy one, and I'd like to get people's feedbacks about the more generalized Vagrant and Virtualbox reqs.  Maybe it's worth changing to `1.8.1+` and `5.0.16+`?

**Comment by nickwallen** [comment]
What versions of Vagrant or Virtualbox have you tested on?  I would be hesitant to throw on a blanket "+" unless we have specifically tested on newer versions.

**Comment by JonZeolla** [comment]
`1.9.2` and `5.1.14r112924` currently among many others in between.  I try to keep those up to date (at least monthly per `brew upgrade`) and they have never caused me an issue.  Also, I have yet to see vagrant/virtualbox versions actually cause any issues, unlike Ansible, etc. which has been much more particular.

I'm open to hearing about other issues people have hit, but I've had dozens of people spin this up with simplified `brew install` commands for vagrant/virtualbox and, as long as the versions are somewhat recent, they have always worked for me so far.  I mean, literally the commands that we have in the README.md right now will install the latest version, and I haven't seen a report on the dev or user mailing lists about issues with that either.

**Comment by ottobackwards** [comment]
maybe we should have a metron brew recipe

**Comment by nickwallen** [comment]
I tend to 'pin' my versions in Brew. I am more risk averse than you. ;)

But your argument sounds reasonable.   You convinced me.  If we start to get negative reports from users, we can always revisit.

**Comment by JonZeolla** [comment]
Ok, sounds good.  The biggest part of this is that I have not been able to find anybody who got Metron working on vagrant after only installing docker via `brew cask install docker`.  I spent some time on it and got relatively nowhere, only fixing it by installing Docker via their dmg, which properly starts the docker daemon.

**Comment by nickwallen** [comment]
> I have not been able to find anybody who got Metron working on vagrant after only installing docker via `brew cask install docker`.

Installing Docker with `brew cask install docker` and then building Metron RPMs works for me (that's the part that needs Docker). What problems have you run into with this?

You do need to start the Docker daemon, but I have to do that all the time (like when I reboot my laptop or just get tired of looking at the whale.)

**Comment by nickwallen** [comment]
+1 Looks good, thanks!

**Pull request closed without merging**
