### PR TITLE
METRON-91 Expose tags and skip tags to Vagrant

### PR DESCRIPTION
**Pull request by dlyle65535**
Tested with the following:
- [x] Clean run "vagrant up"
- [x] Skip tags "vagrant --ansible-skip-tags="ambari" up
- [x] Tags "vagrant --ansible-tags="ambari,metron" up
- [x] ./run_enrichment_role.sh 

Edit - AND
- [x] vagrant destroy -f (sorry, forgot to mention that)

### CODE REVIEW

**Comment by merrimanr** [comment]
+1

**Comment by nickwallen** [comment]
What is the purpose of these scripts;  `run_ansible_role.sh` and `run_enrichment_role.sh`?  I don't understand how I am supposed to use them.  I know these fell out of another PR, but we don't have their use documented anywhere.  Even some commentary at the top of the script itself, would make me a happy camper.

**Comment by dlyle65535** [comment]
Oops, overzealous branch pruning.

@nickwallen - I'll add a readme, good call. Thanks!

**Comment by nickwallen** [comment]
+1 bella!

**Pull request closed without merging**
