### PR TITLE
METRON-237 Remove metron-ui from the code base

### PR DESCRIPTION
**Pull request by mmiklavc**
Removing metron-ui from code base as it is no longer used.

Related Jira - https://issues.apache.org/jira/browse/METRON-237

### CODE REVIEW

**Comment by cestella** [comment]
If we're going to remove metron-ui, which I completely support btw, we are going to need to trim down the  sections in the LICENSE around metron-ui components.

**Comment by dlyle65535** [comment]
Good deal @mmiklavc - always happy to see dead code go away. Did you run this on Vagrant and/or EC2?

**Comment by mmiklavc** [comment]
@dlyle65535 Ran on Vagrant quick dev - verified Kibana UI comes up and Storm topologies are running.

**Comment by dlyle65535** [comment]
+1!

**Comment by cestella** [comment]
+1, looks good

**Pull request closed without merging**
