### PR TITLE
METRON-294 Refactor parser topology builder

### PR DESCRIPTION
**Pull request by nickwallen**
Refactored the `ParserTopologyBuilder` so that is easier to understand and added additional comments and documentation.

### CODE REVIEW

**Comment by cestella** [comment]
Can we please not call this METRON-154, since METRON-154 is about decoupling indexing from enrichment and this is not that?  I do understand that this might be a prerequisite task, but if we could create another JIRA and maybe link the two JIRAs to express the relationship.

**Comment by nickwallen** [comment]
Done

**Comment by james-sirota** [comment]
Does it need METRON-154 in order for this to work?  Is there a hard dependency?  Should i wait to validate this until all the pieces are ready?

**Comment by nickwallen** [comment]
@james-sirota This is completely independent, can be merged in as-is, and has value outside of just METRON-154.

I did a bunch of work for METRON-154 previously that was effectively lost based on how much the code base has diverged.  Really my own fault for not getting it done, but I'd like to merge in chunks of it a time, so that doesn't happen again.

**Comment by james-sirota** [comment]
Is there documentation outside of the file that you forgot to attach?  Or the docs that you are referring to are comments in the code?

**Comment by nickwallen** [comment]
Just in the code; javadoc.

**Comment by james-sirota** [comment]
+1

**Comment by cestella** [comment]
+1, by inspection

**Pull request closed without merging**
