### PR TITLE
METRON-478: Add Michael Miklavcic, Justin Leet, Nick Allen, and David Lyle to Metron website community page

### PR DESCRIPTION
**Pull request by mmiklavc**
Addresses https://issues.apache.org/jira/browse/METRON-478

Confirmed via steps for running jekyll on the wiki - https://cwiki.apache.org/confluence/display/METRON/Website+PR+Merge

Checked page looks correct in Chrome, Firefox, and Safari.

### CODE REVIEW

**Comment by nickwallen** [comment]
Seems like it would make sense to add Committers and PMC members.  Not sure if this is something that requires a vote or some such Apache process.  

Maybe in this PR you could update the page for everyone?  Dave, Justin, Me.

**Comment by mmiklavc** [comment]
I've added the additional requested members. Waiting on feedback if we need any kind of vote on this. This activity was requested as part of my "new committer" activities list per @james-sirota

**Comment by cestella** [comment]
No vote other than normal code review for this pull request.

**Comment by cestella** [comment]
Just make sure you update the asf-site branch with the generated site.

**Comment by mmiklavc** [comment]
Confirmation - apache/asf-site branch has been updated with changes - http://metron.incubator.apache.org/community/

**Pull request closed without merging**
