### PR TITLE
METRON-708: Update metron documentation

### PR DESCRIPTION
**Pull request by JonZeolla**
Primarily these was an update of table formatting and fixing or improving links in documentation.  However some important content was changed, as outlined below.

**Noteworthy changes**
- Added a `brew cask install java` to fulfill a prerequisite of `brew install maven` for macOS install instructions.
- Updated the “must be single quoted” table in `metron-platform/metron-common/README.md`.  Previously, `>` was in a nonexistent fourth column, so it was not being properly displayed via the README.md, and the last row seemed to be a repeat.
  - Question:  Should we add the `in` operator to the “must be single quoted” table?

Please **do not merge** this until the dev list conversation titled “Ansible 2.0.0.2 build issues” comes to a resolution (being sent out soon).

### CODE REVIEW

**Comment by JonZeolla** [comment]
Would anybody be willing to update [this picture](https://github.com/apache/incubator-metron/blob/001b5cc5bc9ecece648730d99285de056319a07c/metron-platform/metron-enrichment/enrichment_arch.png)?  I don't believe we have MySQL doing the enrich as of [this commit](https://github.com/apache/incubator-metron/commit/fa6f3df51b881e84aa7a9525f24c627fa28ca62ecommit).

**Comment by cestella** [comment]
@JonZeolla Good contribution!  Thanks a lot.  

I'd go ahead and document the workaround you proposed in the dev list regarding ansible 2.0.0.2.  Also, if you don't want to modify the picture directly, I'd recommend making a separate JIRA for it and mentioning it independently on the dev list so it doesn't hold up your JIRA.

**Comment by mattf-horton** [comment]
+1 on the changes so far, by inspection.

**Comment by cestella** [comment]
@JonZeolla I suggest treating the PR as it stands to be complete and tracking the ansible and image portion in a follow-on JIRA.  I'm +1 on it as it stands.

**Comment by JonZeolla** [comment]
Ok sounds good to me, I will split those items out to a follow-on.  This can be merged - thanks.

**Comment by simonellistonball** [comment]
Diagram updated in https://github.com/apache/incubator-metron/pull/452

**Pull request closed without merging**
