### PR TITLE
METRON-515: Stellar IS_EMPTY() function does not work as expected

### PR DESCRIPTION
**Pull request by merrimanr**
The "IS_EMPTY" Stellar function is always returning true if the field value is not a String type.  This PR changes the function to only return true when a value is missing, an empty string, or has a null value.  

I also modified the unit test to include a test for an Integer type and removed the test that asserts true when the value is a newly created object.  In my opinion that is not a valid test case.

### CODE REVIEW

**Comment by mmiklavc** [comment]
For context, the original purpose and implementation of IS_EMPTY was exclusively collections and string types. And given the current validation approach, true is returned when an invalid type is passed through. The approach for a non-string type would have been IS_EMPTY(TO_STRING(rcode)). I'm not opposed to this change, but docs should be updated with this as well.

**Comment by cestella** [comment]
Nice 1-liner.  +1 pending a doc change as @mmiklavc suggests to the Stellar annotation and the `README.md` for `metron-common`

**Comment by merrimanr** [comment]
Docs have been updated

**Comment by mmiklavc** [comment]
+1, pending Travis cooperating.

**Pull request closed without merging**
