### PR TITLE
METRON-482 Add logging to GrokParser to indicate supplied TimeZone

### PR DESCRIPTION
**Pull request by justinleet**
Added a few logging statements: both during configure() and during the actual conversion.

### CODE REVIEW

**Comment by dlyle65535** [comment]
@justinleet - did you run this up in Vagrant or elsewhere?

**Comment by justinleet** [comment]
Yeah, ran it up in quick dev and it kicks out exactly what you'd expect when DEBUG is on.

**Comment by mmiklavc** [comment]
+1 by inspection with @justinleet's confirmation of quick dev testing

**Comment by dlyle65535** [comment]
Thanks! +1 as well.

**Pull request closed without merging**
