### PR TITLE
[METRON-9] Adding a gitignore file

### PR DESCRIPTION
**Pull request by sirsean**
The MVN build process creates a bunch of files (ie, the target directories) that we don't need filling up our source control.

### CODE REVIEW

**Comment by ehashman** [comment]
Someone seems to have added a `.gitignore` file since you submitted this pull request. I just did a clean build and the only line I needed to add was

```
opensoc-streaming/OpenSOC-DataLoads/dependency-reduced-pom.xml
```

So perhaps you can reopen this PR by adding that to the new `.gitignore`?

**Comment by sirsean** [comment]
Good idea.

**Comment by sirsean** [comment]
So now there is only one file that's created by the build process and wasn't in the .gitignore file. So that's added here.

**Comment by reaperhulk** [comment]
:+1:

**Comment by ehashman** [comment]
LGTM!

**Pull request merged**
