### PR TITLE
Metron 398: Bump release version to 0.2.1BETA in master

### PR DESCRIPTION
**Pull request by mmiklavc**
Completes https://issues.apache.org/jira/browse/METRON-398

Tested this on quick-dev

I first cleared my .m2 cache just to be sure all dependencies are resolved using the newest version *only*.
`~/.m2$ rm -rf ./org/apache/metron`

**Testing done**

Full dev build
`incubator-metron$ mvn clean install`
rpm build
`incubator-metron/metron-deployment$ mvn clean install -Pbuild-rpms`
quick-dev build
`incubator-metron/metron-deployment/vagrant/quick-dev-platform$ ./run.sh`

### CODE REVIEW

**Comment by cestella** [comment]
+1 by inspection

**Comment by nickwallen** [comment]
Do we need to change something like the following?  There may be others.  This is the new Ambari installer stuff, which I don't know that well.

```
metron-deployment/packaging/ambari/src/main/resources/common-services/INDEXING/0.2.0BETA

**Comment by cestella** [comment]
Oh, agreed, we should make sure the ambari stuff continues to work on this branch.  My +1 is pending that check.

**Comment by mmiklavc** [comment]
@nickwallen Where is it that you're seeing that path? I don't believe that exists any longer.

**Comment by nickwallen** [comment]
@mmiklavc You are right.  I was comparing Github's diff against the wrong branch.  
+1

**Comment by mmiklavc** [comment]
Spun up the Ambari mpack installation and am able to run data through to indexing

**Pull request closed without merging**
