### PR TITLE
Fixed error when start up the system.

### PR DESCRIPTION
**Pull request by AdrianP-**
When start ./run.sh, this error appeard:
fatal: [node1]: FAILED! => {"changed": false, "failed": true, "msg": "value of wait_for_complete must be one of: yes,on,1,true,1,True,no,off,0,false,0,False, got: True"}
In:
  TASK [ambari_config : Deploy cluster with Ambari; http://node1:8080] ***********

### CODE REVIEW

**Comment by dlyle65535** [comment]
Hi,

Thanks for the contribution. Could you tell me what versions of Ansible and Python you're running? I don't actually get this error with Ansible 2.0.0.2 and Python 2.7.11. 

That said, I have tested this patch using those versions and it doesn't introduce any issues.

Thanks again!

-David...

**Comment by AdrianP-** [comment]
I have Python 2.7.6 and Ansible 2.1.0.0.

However, I have a lot of problems with the start up. Fixed this problem, several steps forward get:

`
TASK [metron_elasticsearch_templates : Add Elasticsearch templates for topologies] ***
failed: [node1] (item=/home/tmp/incubator-metron/metron-deployment/roles/metron_elasticsearch_templates/files/es_templates/snort_index.template) => {"content": "", "failed": true, "item": "/home/tmp/incubator-metron/metron-deployment/roles/metron_elasticsearch_templates/files/es_templates/snort_index.template", "msg": "Status code was not [200]: An unknown error occurred: sendall() argument 1 must be string or buffer, not dict", "redirected": false, "status": -1, "url": "http://node1:9200/_template/snort_index"}
failed: [node1] (item=/home/tmp/incubator-metron/metron-deployment/roles/metron_elasticsearch_templates/files/es_templates/yaf_index.template) => {"content": "", "failed": true, "item": "/home/tmp/incubator-metron/metron-deployment/roles/metron_elasticsearch_templates/files/es_templates/yaf_index.template", "msg": "Status code was not [200]: An unknown error occurred: sendall() argument 1 must be string or buffer, not dict", "redirected": false, "status": -1, "url": "http://node1:9200/_template/yaf_index"}
failed: [node1] (item=/home/tmp/incubator-metron/metron-deployment/roles/metron_elasticsearch_templates/files/es_templates/bro_index.template) => {"content": "", "failed": true, "item": "/home/tmp/incubator-metron/metron-deployment/roles/metron_elasticsearch_templates/files/es_templates/bro_index.template", "msg": "Status code was not [200]: An unknown error occurred: sendall() argument 1 must be string or buffer, not dict", "redirected": false, "status": -1, "url": "http://node1:9200/_template/bro_index"}
`

And if I delete that step, next I get this:

`TASK [solr : Start Solr] *******************************************************
fatal: [node1]: FAILED! => {"changed": false, "failed": true, "msg": "service solr does not support chkconfig"}
`

**Comment by dlyle65535** [comment]
That makes sense. Please use the versions outlined here: https://github.com/apache/incubator-metron/blob/master/metron-deployment/vagrant/full-dev-platform/README.md.

Ansible 2.1.0.0 is not currently supported.

**Comment by AdrianP-** [comment]
Perfect, but we have a problem because that packet doesn't exist in ppa: https://launchpad.net/~ansible/+archive/ubuntu/ansible

**Comment by dlyle65535** [comment]
Can you install it using pip?

**Comment by james-sirota** [comment]
Here are instructions on downgrading ansible.  https://cwiki.apache.org/confluence/display/METRON/Downgrade+Ansible Can this pull request be closed?

**Comment by AdrianP-** [comment]
Yes, with pip works correctly. Thanks!

**Comment by nickwallen** [comment]
@AdrianP- Glad that it is working for you.  Hope to hear more about your experiences with Metron.

Unfortunately, we cannot close this PR because we are not admins.  But you are always able to close your own PRs.

**Comment by AdrianP-** [comment]
@nickwallen Sorry. Do it

**Pull request closed without merging**
