### PR TITLE
METRON-527: Connection pool shut down seen when running threatintel_t…

### PR DESCRIPTION
**Pull request by justinleet**
…axii_load.sh script

### CODE REVIEW

**Comment by justinleet** [comment]
The Taxii HttpClient closes connections in callTaxiiService as seen here:
https://github.com/TAXIIProject/java-taxii/blob/master/src/main/java/org/mitre/taxii/client/HttpClient.java#L335

Because TaxiiHandler attempted to reuse a closed connection, the error was seen.  The fix is just to ensure the connection is created fresh before each call.  Integration test is updated to just call the run() method twice without caring about results to ensure that the connection doesn't explode.

In addition, this was tested in quick-dev using a slightly modified version (to work with Vagrant) of https://community.hortonworks.com/articles/59698/pushing-stixtaxii-feeds-from-opentaxii-server-into.html, where the playbook was run with
`ansible-playbook --private-key=./vagrant/quick-dev-platform/.vagrant/machines/node1/virtualbox/private_key -i 192.168.66.121, playbooks/install-opentaxii.yml -e ansible_python_interpreter=python -e ansible_user=vagrant -vvvv`
with the IP being quick-dev's IP and the install-opentaxii script modified to reflect this.

After the change, polling continues until ended and hbase dumps grow as new records are added.

**Comment by cestella** [comment]
+1 by inspection

**Comment by mmiklavc** [comment]
+1 by inspection

**Comment by justinleet** [comment]
Please hold off on merging this a bit.  Anand and I are looking into an issue that is almost certainly separate, but doing due diligence.

**Comment by justinleet** [comment]
I'm satisfied with my PR after further investigation.

**Pull request closed without merging**
