### PR TITLE
METRON-334 Travis cache Maven dependencies

### PR DESCRIPTION
**Pull request by justinleet**
Adding .m2 directory to caching, so that it is reused on subsequent builds.

### CODE REVIEW

**Comment by justinleet** [comment]
Initial Travis build, from before the cache is populated, downloads everything
https://travis-ci.org/justinleet/incubator-metron/builds/145862346#L174

Afterwards, on a whitespace commit no longer downloads the dependencies
https://travis-ci.org/justinleet/incubator-metron/builds/145870931#L171

**Comment by mmiklavc** [comment]
+1 (non-binding)
28 min vs 27:40... I had hoped this would have made a bigger impact

**Comment by justinleet** [comment]
The timings are really inconsistent in general. Some builds (essentially the same) earlier were taking anywhere as low as 17 minutes.  It makes it hard to tell how worthwhile timings are, even in close proximity.

**Comment by dlyle65535** [comment]
+1, worked and created a 975MB cache.

**Comment by cestella** [comment]
+1 via inspection.  Great job, Justin.

**Pull request closed without merging**
