### PR TITLE
METRON-356 Modify Storm topology.classpath via configuration 

### PR DESCRIPTION
**Pull request by mmiklavc**
This PR completes - [https://issues.apache.org/jira/browse/METRON-356](https://issues.apache.org/jira/browse/METRON-356)

The code changes leverage Storm's built-in classpath properties for adding additional files to the classpath instead of modifying Metron jar file internals to include items required on the classpath.

I successfully tested this on full dev platform.

Additional info - [https://issues.apache.org/jira/browse/STORM-54](https://issues.apache.org/jira/browse/STORM-54)

**Testing**

Standard deployment that includes deployment via Ambari. Ensure that the pipeline runs without Exceptions from the parsers through to indexing in Elasticsearch. Verify you see indexes being populated in Kibana. Note: If you're seeing exceptions in the full dev platform in Vagrant, you might need to stop YARN, MR2, and any other processes not necessary to verify indexing works correctly.

### CODE REVIEW

**Comment by dlyle65535** [comment]
This looks really good, @mmiklavc  I suspect you meant Ansible above? Perhaps you can re-title this to "Enable topology classpath to be updated via configuration"?
I'll run it up tomorrow morning and let you know.

**Comment by mmiklavc** [comment]
It's a setting in Ambari that exposes the functionality, which is set via the Ansible scripts. I will rename it per your recommendation.

**Comment by dlyle65535** [comment]
Thanks- it'll help later when we modify the Ambari setup scripts to accept the setting. :)

**Comment by dlyle65535** [comment]
+1. Ran it up on EC2- worked great!

**Comment by cestella** [comment]
+1 by inspection, great job!

**Pull request closed without merging**
