### PR TITLE
METRON-646: Add index templates to metron-docker

### PR DESCRIPTION
**Pull request by kylerichardson**
Enhance metron-docker environment by automatically deploying index templates to elasticsearch as part of the container startup.

I've also included a maven clean goal for the metron-docker project for easier build/rebuild.

Test plan and rebase with master to follow shortly.

### CODE REVIEW

**Comment by nickwallen** [comment]
Hi @kylerichardson - I don't want to throw cold water on your effort, but I am hesitant to create a third deployment code base for `metron-docker` (in addition to MPack and Ansible.)  Do you think that is what this is or would become?

Besides just the index templates, we'd have to add and support a lot of other functionality too.  Seems like we should have a goal to move towards a single deployment mechanism that works across multiple platforms (Docker, Metal, etc).

I don't even know if this is feasible, but it may be worth a community discussion.  I'll kick something off.

**Comment by kylerichardson** [comment]
Good point, @nickwallen. My hope for metron-docker is as a lightweight alternative to vagrant for development. That said, I would hate to see it become a large overhead for the community.

Thanks for starting a dev list discussion. I'll post my thoughts there.

-Kyle

**Comment by kylerichardson** [comment]
bump... I read back through the discuss thread from the dev list and we didn't land on any specifics. There seems to be general agreement that metron-docker:
- fulfills a current need/desire for targeted development and testing (e.g. parsers)
- could be used to make integration testing quicker and easier (requires exploration)

How do we want to move this forward? I have this and a follow-on PR ready to go for adding HDFS into metron-docker.

**Comment by merrimanr** [comment]
@kylerichardson I will get this reviewed today

**Comment by merrimanr** [comment]
Works great.  I have just one very small request.  Can you update the Usage section of the README (where it lists the UI addresses) to point to the Elasticsearch head plugin instead of just "http://192.168.99.100:9200/"?  That will keep someone from having to go research how to access that plugin.

Other than that this gets my +1.  Thanks for the contribution.

**Comment by kylerichardson** [comment]
Thanks, @merrimanr! I'll get that change pushed out later today. Waiting on
#462 to be merged to fix the build errors we're seeing and then I'll rebase
and push.

**Comment by merrimanr** [comment]
+1 from me

**Pull request closed without merging**
