### PR TITLE
METRON-700: Add hadoop container to metron-docker

### PR DESCRIPTION
**Pull request by kylerichardson**
### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root incubating-metron folder.
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via site-book/target/site/index.html.

EDIT: Removed N/A items from template.

### CODE REVIEW

**Comment by kylerichardson** [comment]
### Description
Added a Hadoop/HDFS container to metron-docker. As part of the change, the geo enrichment database is now staged in HDFS to closer mimic a real cluster deployment.

### Testing
Successfully ran through testing with bro sensor data based on the test plan previously documented in the [README](https://github.com/apache/incubator-metron/blob/master/metron-docker/README.md#run-sensor-data-end-to-end).

**Comment by merrimanr** [comment]
Looks good.  The "Run sensor data end to end" didn't work for me and I had to make a couple changes to get data flowing through the indexing topology.  When I started the indexing topology, I got insufficient indexing config errors and realized the index zookeeper configs are not deployed to the kafkazk image.  Once I added those and uploaded to zookeeper, everything worked and I could see data archived in the HDFS container.  Did you run into that?

I believe the missing index configs is a separate issue and not related to the PR.  I will package the changes I had to make up into a follow-on PR.  Nice work +1.

**Comment by merrimanr** [comment]
While reviewing this I had an idea for another PR that would make this easier to use.  The slowest part of spinning this up is downloading the kafka and hbase distributions.  What would you think of splitting these Dockerfiles into 2 separate images:  one with just the service installed (kafka or hbase) and another that extends the service and installs the Metron bits on top?  This would allow us to quickly deploy Metron changes and rebuild.  To get that to work we would need to a way to get the base image installed locally.  Initially this could just be a build script that needs to be run once before spinning the application up and long term it could live in Docker Hub.  

What do you think of this idea?  Would it be helpful?  I'm a little hesitant to add a manual step that needs to be done before the application will work but I don't want to add that hook into the build process, even if we do add a check for a running Docker machine.  Maybe publishing to Docker Hub now is the answer.  Any feedback or ideas?

**Comment by kylerichardson** [comment]
@merrimanr That's interesting. I did get warnings in the logs about the indexing configs but it seemed like the defaults applied and I was still able to see data indexed into HDFS. Did you have to make any other modifications? Do you want me to add in the indexing configs to zookeeper as part of this PR? It wouldn't be difficult.

I like the idea of creating base kafka/zookeeper and hbase container images that could be hosted on Docker Hub. This aligns with how we are handling the other containers and allows us to separate the Metron specific aspects into dedicated Dockerfiles/images. I would be in favor of going the Docker Hub route sooner than later to avoid the additional manual steps.

**Comment by merrimanr** [comment]
If you don't mind adding the indexing configs in this PR that would be great.  I had to make 4 changes to get it to work:
- updated the pom.xml to copy the indexing archive into kafkazk
- updated the kafkazk Dockerfile to add the indexing archive and extract it
- updated the init-zk.sh script to create the /metron/topology/indexing path in zookeeper
- added /compose/kafkazk/indexing to .gitignore

Thanks for the feedback, I'll work on getting base kafka and hbase containers uploaded to Docker Hub.

**Comment by merrimanr** [comment]
Bump.  I think this is ready to go @kylerichardson.

**Comment by kylerichardson** [comment]
@merrimanr Just pushed the changes for adding the indexing configs. Should be ready to go now. Can you give it another glance?

**Comment by merrimanr** [comment]
Looks good.  I like the packages approach instead of listing out individual modules.  +1

**Comment by kylerichardson** [comment]
Thanks! Next time the storm Dockerfile needs a tweak, I'll rework it to use the packages approach too.

**Pull request closed without merging**
