### PR TITLE
METRON-902 ES improperly indexes Bro logs

### PR DESCRIPTION
**Pull request by JonZeolla**
## Contributor Comments
It appears that `bro_index.template` regressed a bit when it was migrated to the ambari mpack.  If you run this up in vagrant and let the bro sensor-stub run for a while you will see ES indexing issues for dns logs because answers is not always an IP address.  This fixes that, and I will try to get a look at the whole bro ES indexing template for other issues, as a part of METRON-508.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [X] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [X] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [X] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root incubating-metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [X] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by nickwallen** [comment]
Good catch, @JonZeolla   I am trying to think of a way we could automate the testing of this thing.  Somehow grab a particular record that triggers the issue and make sure thats part of our test suite.  Don't have any ideas right now, but I need to noodle on that some more (and get some more coffee).

**Comment by ottobackwards** [comment]
We should look at extending the indexing integration tests.... maybe.
another idea for me is if the ES templates get bundled with the parsers, we can have new parser integration tests for that

**Comment by nickwallen** [comment]
Or maybe we need something new, specifically for these templates.

**Comment by nickwallen** [comment]
How should we test this @JonZeolla ?  Can you layout some steps for us?

**Comment by JonZeolla** [comment]
The most recent time I noticed the issue was when I was testing #510.  In that case, I spun up full-dev and pushed [these logs](https://github.com/JonZeolla/incubator-metron/blob/master/metron-platform/metron-integration-test/src/main/sample/data/bro/raw/BroExampleOutput) onto the bro kafka topic and noticed that only 7 of them were making it to ES, and it was spitting the error messages into the storm logs for the indexing worker.  If this fix works properly, all 10 of those logs should now get properly indexed.

**Comment by ottobackwards** [comment]
We should attach those logs to a jira about expanding the parser es integration tests

**Comment by JonZeolla** [comment]
Ok, this is ready for review.  It essentially re-implements METRON-403, METRON-510, and METRON-517.

**Comment by JonZeolla** [comment]
bump

**Comment by nickwallen** [comment]
+1 by inspection

**Pull request closed without merging**
