### PR TITLE
METRON-668: Remove the "tickUpdate" profile config and make the "init" phase not reset variables

### PR DESCRIPTION
**Pull request by cestella**
Please see description at [METRON-668](https://issues.apache.org/jira/browse/METRON-668) for a full description.

### CODE REVIEW

**Comment by mmiklavc** [comment]
Excellent. And I need these fixes for some outlier analysis with HLLP and MAD. +1 by inspection.

**Comment by nickwallen** [comment]
I like this as it simplifies the Profile configuration.

How did you test this?  Did you run any profiles on "Quick Dev"?

**Comment by cestella** [comment]
@nickwallen running as we speak.  The test plan will be to generate some data like we do for the MAD outliers and construct a couple simple profiles.  I'll make it a bit more explicit after I do it. :)

**Comment by cestella** [comment]
Ok, test is complete, I made sure the profiler worked.  I also adjusted the timeout on the indexing integration tests so that travis doesn't barf.

**Comment by cestella** [comment]
The explicit test that was done on quickdev was following the Median Absolute Deviation scenario in `metron-statistics`

**Comment by cestella** [comment]
By the way, please don't merge this.  I'm using this branch to figure out what's going on with the build failures.

**Pull request closed without merging**
