### PR TITLE
METRON-264: Create Docker container to simplify management of deploy dependencies	

### PR DESCRIPTION
**Pull request by dlyle65535**
Provides a Docker container for running deployment.

Tested with EC2 and on bare metal.

### CODE REVIEW

**Comment by nickwallen** [comment]
What's your thought process on using a `contrib` directory?  What else would live in there?

I think `metron-deployment` desperately needs some reorganization.  Maybe your thought process with `contrib` can help that reorganization.

**Comment by dlyle65535** [comment]
@nickwallen - I agree about the reorg. Will likely happen organically as a result of METRON-214.

Contrib is for stuff that's loosely related, but not essential to the project. I should probably put the packer stuff there as well.

**Comment by nickwallen** [comment]
+1

**Comment by james-sirota** [comment]
+1 great job

**Pull request closed without merging**
