### PR TITLE
METRON-298 Remove the effective_tld_names.dat files

### PR DESCRIPTION
**Pull request by cestella**
Remove these files because they are mozilla licensed and seem to cause problems during the releases. We have a different way of doing this now and the adapter using them should be mothballed.
Be sure to remove the MPL reference in the LICENSE file too

### CODE REVIEW

**Comment by james-sirota** [comment]
+1

**Comment by james-sirota** [comment]
I ran this up in AWS and it worked ok.  Did anyone else check?

**Comment by cestella** [comment]
Just for posterity, I ran it up in vagrant

**Comment by dlyle65535** [comment]
I've been trying, but it's AWS is fighting me.

**Pull request closed without merging**
