### PR TITLE
METRON-867: In the event that we graduate, remove incubating from the website and documentation

### PR DESCRIPTION
**Pull request by cestella**
## Contributor Comments
NOTE:
* This is not an indication of graduation status.
* I did not change any link to the archives of our lists on the website.

To test this:
* Spin up full-dev and make sure things still work (I touched one python file, but I think it's fine).
* Spin up the website from this PR and make sure no incubator logos or other indication of incubation.
* Generate the docs and ensure they contain no indication of incubation

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron (Incubating).  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  bin/generate-md.sh
  mvn site:site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by mmiklavc** [comment]
There are some incubator references remaining in the site-book

```
{12:24}~/devprojects/incubator-metron/site-book:4529d26 ✓ ➭ grep --exclude "*.log" --exclude "*.bak" -inR 'incubat' *
README.md:14:In any git clone of incubator-metron containing the site-book subdirectory,
README.md:25:file:///your/path/to/incubator-metron/site-book/target/site/index.html
pom.xml:30:             <connection>scm:git:https://git-wip-us.apache.org/repos/asf/incubator-metron.git</connection>
pom.xml:31:             <developerConnection>scm:git:https://git-wip-us.apache.org/repos/asf/incubator-metron.git</developerConnection>
pom.xml:33:             <url>https://git-wip-us.apache.org/repos/asf/incubator-metron</url>
src/site/markdown/index.md:1:[![Build Status](https://travis-ci.org/apache/incubator-metron.svg?branch=master)](https://travis-ci.org/apache/incubator-metron)
src/site/markdown/index.md:65:1. git clone --recursive https://github.com/apache/incubator-metron
src/site/markdown/index.md:66:2. [Download ZIP](https://github.com/apache/incubator-metron/archive/master.zip)
src/site/markdown/metron-deployment/index.md:48:Navigate to `incubator-metron/metron-deployment/vagrant/full-dev-platform` and run `vagrant up`.
src/site/markdown/metron-deployment/index.md:51:Navigate to `incubator-metron/metron-deployment/vagrant/quick-dev-platform` and run `vagrant up`.
src/site/markdown/metron-deployment/packaging/docker/ansible-docker/index.md:17:1. docker run -it -v \<project-directory\>:/root/incubator-metron ansible-docker:2.0.0.2 bash
src/site/markdown/metron-deployment/packaging/docker/ansible-docker/index.md:18:2. cd /root/incubator-metron
src/site/markdown/metron-deployment/vagrant/Kerberos-setup.md:9:    cd incubator-metron/metron-deployment/vagrant/full-dev-platform
src/site/markdown/metron-deployment/vagrant/Kerberos-setup.md:257:24. Push some sample data to one of the parser topics. E.g for bro we took raw data from [incubator-metron/metron-platform/metron-integration-test/src/main/sample/data/bro/raw/BroExampleOutput](../../metron-platform/metron-integration-test/src/main/sample/data/bro/raw/BroExampleOutput/index.html)
src/site/markdown/metron-deployment/vagrant/quick-dev-platform/index.md:28:  cd incubator-metron
src/site/markdown/metron-interface/metron-config/index.md:19:1. Copy `incubator-metron/metron-interface/metron-config/target/metron-config-METRON_VERSION-archive.tar.gz` to the desired host.
src/site/markdown/metron-sensors/fastcapa/index.md:202:    cd incubator-metron/metron-sensors/fastcapa
src/site/markdown/metron-sensors/pycapa/index.md:7:Pycapa performs network packet capture, both off-the-wire and from Kafka, which is useful for the testing and development of [Apache Metron](https://github.com/apache/incubator-metron).  It is not intended for production use. The tool will capture packets from a specified interface and push them into a Kafka Topic.
src/site/markdown/Upgrading.md:21:Please see the description of the configurations in the indexing [README](https://github.com/apache/incubator-metron/tree/Metron_0.3.1/metron-platform/metron-indexing#sensor-indexing-configuration)
target/site/index.html:161:            <p><a class="externalLink" href="https://travis-ci.org/apache/incubator-metron"><img src="https://travis-ci.org/apache/incubator-metron.svg?branch=master" alt="Build Status" /></a></p>
target/site/index.html:199:<li>git clone &#x2013;recursive <a class="externalLink" href="https://github.com/apache/incubator-metron">https://github.com/apache/incubator-metron</a></li>
target/site/index.html:201:<li><a class="externalLink" href="https://github.com/apache/incubator-metron/archive/master.zip">Download ZIP</a></li>
target/site/metron-deployment/index.html:272:<p>Navigate to <tt>incubator-metron/metron-deployment/vagrant/full-dev-platform</tt> and run <tt>vagrant up</tt>.</p></div>
target/site/metron-deployment/index.html:275:<p>Navigate to <tt>incubator-metron/metron-deployment/vagrant/quick-dev-platform</tt> and run <tt>vagrant up</tt>.</p></div></div>
target/site/metron-deployment/packaging/docker/ansible-docker/index.html:226:<li>docker run -it -v &lt;project-directory&gt;:/root/incubator-metron ansible-docker:2.0.0.2 bash</li>
target/site/metron-deployment/packaging/docker/ansible-docker/index.html:228:<li>cd /root/incubator-metron</li>
target/site/metron-deployment/vagrant/Kerberos-setup.html:253:<pre>cd incubator-metron/metron-deployment/vagrant/full-dev-platform
target/site/metron-deployment/vagrant/Kerberos-setup.html:532:<p>Push some sample data to one of the parser topics. E.g for bro we took raw data from <a href="../../metron-platform/metron-integration-test/src/main/sample/data/bro/raw/BroExampleOutput/index.html">incubator-metron/metron-platform/metron-integration-test/src/main/sample/data/bro/raw/BroExampleOutput</a></p>
target/site/metron-deployment/vagrant/quick-dev-platform/index.html:274:<pre>  cd incubator-metron
target/site/metron-interface/metron-config/index.html:187:<p>Copy <tt>incubator-metron/metron-interface/metron-config/target/metron-config-METRON_VERSION-archive.tar.gz</tt> to the desired host.</p></li>
target/site/metron-sensors/fastcapa/index.html:440:<pre>cd incubator-metron/metron-sensors/fastcapa
target/site/metron-sensors/pycapa/index.html:188:<p>Pycapa performs network packet capture, both off-the-wire and from Kafka, which is useful for the testing and development of <a class="externalLink" href="https://github.com/apache/incubator-metron">Apache Metron</a>. It is not intended for production use. The tool will capture packets from a specified interface and push them into a Kafka Topic.</p></div>
target/site/Upgrading.html:179:<p>Please see the description of the configurations in the indexing <a class="externalLink" href="https://github.com/apache/incubator-metron/tree/Metron_0.3.1/metron-platform/metron-indexing#sensor-indexing-configuration">README</a></p></div>
```

**Comment by cestella** [comment]
Yes, those are referencing our github repo, which is "incubator-metron".  We would have to change those references after we move infrastructure around post-graduation (if it happens).  I didn't want to break functionality in the interrim while that happens.

**Comment by mmiklavc** [comment]
OK, that makes sense. Spinning up full dev now.

**Comment by JonZeolla** [comment]
Am I missing something?  I thought we were approved for graduation as of last night.

**Comment by cestella** [comment]
Yeah, just waiting for the press release before we make this too public.

**Comment by mmiklavc** [comment]
+1. Spun up full dev and verified index is still populating via `curl -XGET "node1:9200/bro*/_count"`. Also spun up the site and grepped for incubator|incubating in the source files.

**Comment by justinleet** [comment]
+1, I took a look through the site and didn't see anything wrong and also searched the code a bit for signs of incubation.

Do we have tickets for any of the follow-on work mentioned, e.g. the changing the repo references?

**Comment by cestella** [comment]
No, no follow-on tickets as of yet.  I was planning on looking at it Monday after the press release and formulating a plan and discussing with the community any impact that might have.

If anyone wants to take a gander earlier than that and create some JIRAs, I'd not be opposed to that.  It doesn't take the VP, just a PMC member to push the buttons, but pretty much anyone in the community can formulate a plan.

**Comment by justinleet** [comment]
I'm fine with looking at it Monday.  I may take a quick look if there's any JIRAs from other projects we can steal as a starting template, but if not we can start running through the graduation guides and creating tickets as needed.

**Pull request closed without merging**
