### PR TITLE
METRON-433: Documentation update

### PR DESCRIPTION
**Pull request by cestella**
It has been a while since we had a holistic documentation review. I reviewed the README.md and
* Rearranged content to better reflect the current segmentation of the model, moving a lot of content from metron-common
* Added documentation and examples for MaaS
* Added topology diagrams for the parser/enrichment topologies.
* Added relevant examples of using stellar to do enrichments.
* Made the stellar user defined functions provided up-to-date.

### CODE REVIEW

**Comment by james-sirota** [comment]
+1

**Comment by anandsubbu** [comment]
Would the Storm topology visualization diagram work for the parser, enrichment and indexing illustration? 

Attached is a sample image for the parser topology. I can work on getting rid of the numbers beneath the names.

parser-topology

**Comment by JonZeolla** [comment]
@anandsubbu What I was leaning towards was something that would match up with the Storm documents - more like [this](https://github.com/apache/storm/blob/master/docs/images/topology.svg) or, even better (IMO), [this](https://github.com/apache/storm/blob/master/docs/images/storm-flow.png).  The hope is to spark a "I've seen that before!" kind of moment for the reader.

**Comment by anandsubbu** [comment]
Hi @JonZeolla, please see if the attached sample for Enrichment is better.
enrichment-architecture

**Comment by JonZeolla** [comment]
@anandsubbu That's exactly what I had in mind.  @cestella, thoughts?

**Comment by cestella** [comment]
@anandsubbu I love it!  Thank you so much!  

My only concern is in adopting it in this PR, I won't get to credit you with the commit.  You have two choices:
* Attach the images here and I'll update this PR
* I'll merge this PR and you can submit a follow-on PR with updated doc images

The benefit of the second one is that we'll give you credit for the PR and commit.  What do you think?

**Comment by anandsubbu** [comment]
Hi @cestella and @JonZeolla, great. I will go ahead and create similar ones for the remaining diagrams as well. 

Either way works fine by me, though I would be super excited to get a chance at my very first commit :).

**Comment by cestella** [comment]
You got it; I'll merge this guy later on today and you can submit a new PR that replaces the images. :)  Thanks for the contribution!

**Comment by mmiklavc** [comment]
@anandsubbu @JonZeolla Thank you both for the feedback and contributions!

**Pull request closed without merging**
