### PR TITLE
METRON-623: Management UI

### PR DESCRIPTION
**Pull request by merrimanr**
Initial version of the Management UI using Angular2.  Currently it is bundled and served from the metron-rest Spring application server but can be easily decoupled and run in it's own web server.  See the metron-rest README for instructions on deploying.  This UI also uses angular-cli and more information can be found at https://github.com/angular/angular-cli.

### CODE REVIEW

**Comment by ottobackwards** [comment]
Does this depend on the docker branch being landed first?

**Comment by merrimanr** [comment]
It does include the docker branch commits but does not directly depend on
it if I'm not mistaken.

**Comment by JonZeolla** [comment]
Can we get the merge conflicts resolved here?  Now that #393 (docker) got merged into master, this needs a bit of an update.

**Comment by merrimanr** [comment]
No problem.  This PR is also dependent on METRON-503 which is currently being updated.  Will get the merge conflicts resolved soon.

**Comment by mattf-horton** [comment]
Wow, @merrimanr , there are currently 320 files changed in this PR.  I don't know how to start reviewing this.

Hopefully most or a lot of those go away when METRON-622 and METRON-503 are subtracted.  Could you please consider posting a PR against a branch that already has those committed, so we can see just the changes affected by this feature?  Alternatively you could use [Apache Reviewboard](https://reviews.apache.org/r/) to post such a diff.  Thanks.

**Comment by merrimanr** [comment]
I'm going to close this until METRON-503 gets merged.  Sorry for the distraction.

**Pull request closed without merging**
