### PR TITLE
METRON-705: Parallelize the build in travis to the extent that is obvious

### PR DESCRIPTION
**Pull request by cestella**
Travis suggests [here](https://blog.travis-ci.com/2012-11-28-speeding-up-your-tests-by-parallelizing-them/) that for situations where the integration get chunky, one can parallelize them using their build matrix functionality. Also, if we can separate those out, we can also process-parallelize the unit and build.

Currently the build time is cut roughly in half to 24 minutes wall-clock.

**NOTE: This is just a stopgap that requires no code changes to lower build wall-clock times.  This is not intended to replace work parallelizing the integration tests or making the build take less time.**

### CODE REVIEW

**Comment by ottobackwards** [comment]
So to test this - if you have travis set up for your git account, I think you just push it to a branch in your repo and let travis build it?

**Comment by mmiklavc** [comment]
@ottobackwards Yes, that should do it.

**Comment by cestella** [comment]
Yep, that's how I did it.  You can see a build of it on my account [here](https://travis-ci.org/cestella/incubator-metron/builds/199349340)

**Comment by ottobackwards** [comment]
I'm doing it now

**Comment by ottobackwards** [comment]
#14 passed

 Elapsed time 43 min 10 sec
 Total time 1 hr 6 min 21 sec

**Comment by ottobackwards** [comment]
integration tests took 43 minutes

**Comment by cestella** [comment]
Wow, that's interesting @ottobackwards ; seems like this is very variable.  Could you run it again and see if it's consistent?

**Comment by cestella** [comment]
Looking at those logs, it appears that the first phase, the build (not the actual integration tests) is 4 minutes 39 seconds in my integration-test phase [build](https://api.travis-ci.org/jobs/199327334/log.txt?deansi=true) on travis vs 21 minutes 53 seconds on [yours](https://api.travis-ci.org/jobs/199370358/log.txt?deansi=true)

**Comment by ottobackwards** [comment]
you bet.... btw -the build on this pr isn't even going at all

**Comment by cestella** [comment]
@ottobackwards Yeah, we have to use the apache [job queue](https://blogs.apache.org/infra/entry/apache_gains_additional_travis_ci) (which has 30 parallel builds) on travis rather than the big one for all open source projects.  I suspect it gets slammed during the day.

**Comment by cestella** [comment]
Ok, this was just too volatile.  I also got 43 minutes for the integration test run.  It's probably worth investigating in the future, but for now I'm going to revert to just one container:
* parallelize the package phase
* parallelize the unit test phase
* run the integration tests in serial

**Comment by cestella** [comment]
Also, with only 30 parallel builds available across all apache projects, asking for 2 separate containers per build might be greedy. ;)

**Comment by ottobackwards** [comment]
#14.1 passed

 Elapsed time 23 min 28 sec
On my second try around 5pm

**Comment by cestella** [comment]
I reran this 7 times on my travis account for the most recent commit and the times were on average 32 minutes 53 seconds

* 28m 17s
* 28m 13s
* 46m 28s
* 35m 53s
* 26m 26s
* 33m 0s
* 31m 57s

build_times

**Comment by justinleet** [comment]
+1, I was able to run this up in Travis setup on my repo without issue and it ran right in the middle of the time range listed

**Pull request closed without merging**
