### PR TITLE
METRON-368 Simplify Profile Configuration with Sensible Defaults

### PR DESCRIPTION
**Pull request by nickwallen**
### [METRON-368](https://issues.apache.org/jira/browse/METRON-368)

Note: This change depends on #208 #212.  The diff will be easier to grok once those PRs have been merged.

### Changes
The user should not need to define every configuration field.  This will help simplify the configuration for many types of profiles.

* If the user does not define 'onlyif', then all messages should be included in a profile.  
* If the user does not define 'init' then no vars should be initialized.
* If the user does not define 'update' then no vars should be updated.

### Testing
* Create a profile with no 'onlyif' field.  All messages should be applied to the profile.  
* Create a profile with no 'init' field. The profiler should not error.
* Create a profile with no 'update' field.  The profiler should not error

### CODE REVIEW

**Comment by cestella** [comment]
+1 by inspection

**Comment by nickwallen** [comment]
In some cases, the HBaseTestingUtility does not work unless you specify it this way.  Need to update.

```
Configuration config = HBaseConfiguration.create();
        config.set("hbase.master.hostname", "localhost");
        config.set("hbase.regionserver.hostname", "localhost");
        HBaseTestingUtility testUtil = new HBaseTestingUtility(config);
```

**Comment by nickwallen** [comment]
@cestella Give this one more look before we merge it.  I added the additional configuration elements for `HBaseTestingUtility` and also suppressed excessive logging coming out of the `metron-hbase` unit tests.

**Comment by cestella** [comment]
Yep I took a look last night and just did again.  Looks good

**Comment by nickwallen** [comment]
About to get my merge on.

**Pull request closed without merging**
