### PR TITLE
METRON-336 Update README.md to use brew instead of pip for ansible 2.0.0.2 install

### PR DESCRIPTION
**Pull request by jfrazee**
This is the same as #197 but rebased correctly.

### CODE REVIEW

**Comment by dlyle65535** [comment]
Hi,

Thanks for the contribution. Is there a reason you prefer brew over pip?

**Comment by jfrazee** [comment]
@dlyle65535 It's mostly about consistency I think, but it should also be easier (not impossible) to manage the multiple ansible versions inside homebrew than with pip. Include both sets of instructions?

**Comment by dlyle65535** [comment]
I don't really have a strong preference, just curious.

**Comment by cestella** [comment]
I get ya, yeah, we have half the instructions in brew and then the ansible switching in pip.    Sounds good, I'm +1.

**Comment by nickwallen** [comment]
+1

**Pull request closed without merging**
