### PR TITLE
METRON-196: Deployment Fails Without Ansible 2.0.0.2

### PR DESCRIPTION
**Pull request by dlyle65535**
## Contributor Comments
This changeset allows deployment with Ansible 2.0.0.2 and 2.2.2.0. 

I also added a version check as a pre-task to the top of the two entry playbooks, so deployment will now fail with a clearer error message if it is run on untested Ansible versions. 

@JonZeolla - this is the branch that (I hope) takes care of your issue. Please update Ansible to 2.2.2.0 and give it a whirl when you can. I setup a virtualenv to test it out, I'd recommend you do the same.

**Testing**
For those wishing to remain on 2.0.0.2, nothing should change, simply run the deployment of your choice.

For those wishing to test on 2.2.2.0, do the following:

1. Setup virtual environment for testing.

```
pip install virtualenv
cd ~
virtualenv -p /usr/bin/python2.7 test_ansible
source ~/test_ansible/bin/activate
pip install ansible
pip install boto
```
After this, your prompt will begin with (test_ansible) indicating you're in the virtual Python environment.

2. Run deployment of your choosing.

3. Type _deactivate_ to return to your normal Python environment. 

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron (Incubating).  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [X] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [N/A] Have you included steps to reproduce the behavior or problem that is being changed or addressed.
- [X] Have you included steps or a guide to how the change may be verified and tested manually?
- [X] Have you ensured that the full suite of tests and checks have been executed in the root incubating-metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [N/A] Have you written or updated unit tests and or integration tests to verify your changes?
- [N/A] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [X] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent? (Full Dev and EC2)

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  bin/generate-md.sh
  mvn site:site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by cestella** [comment]
This is great work @dlyle65535 I'll reserve my +1 for immediately after Jon tries it out.

**Comment by JonZeolla** [comment]
Taking a look at this today.

**Comment by JonZeolla** [comment]
I'm getting `{"dns": {"ts":1490980024.000000.58808,"uid":"CmLZ8q1IzktXz75Bq"` from sensor-stubs, where it should be `{"dns": {"ts":1484169493.58808,"uid":"CmLZ8q1IzktXz75Bq"` according to [this](https://github.com/apache/incubator-metron/blob/master/metron-deployment/roles/sensor-stubs/files/bro.out).  Not sure why that extra `.000000` is being inserted.

**Comment by dlyle65535** [comment]
@JonZeolla - That looks like data was sent before the templates were loaded. Is that possible? I had clean data on all my test runs.

**Comment by JonZeolla** [comment]
It looks like what I found earlier was an unrelated issue in [start-bro-stub](https://github.com/apache/incubator-metron/blob/master/metron-deployment/roles/sensor-stubs/templates/start-bro-stub#L50-L51), which I  was able to fix under [METRON-815](https://issues.apache.org/jira/browse/METRON-815).  I'm finishing that some testing on that and then taking another look at this.

**Comment by JonZeolla** [comment]
Ok I've spun this up a few different ways now and I'm consistently seeing no indexes being created in ES, but I am successfully getting what appears to be valid snort and bro logs to the indexing topic.  
```
[vagrant@node1 /]$ curl -XGET 'localhost:9200/_cat/indices?v&pretty'
health status index   pri rep docs.count docs.deleted store.size pri.store.size
green  open   .kibana   1   0         52            0     57.6kb         57.6kb
```

Storm UI is showing no activity in the indexing bolts/spout.
screen shot 2017-04-02 at 10 25 40 pm
The worker.log for indexing shows
```
2017-04-03 02:15:29.420 STDERR [INFO] Error: Could not find or load main class ${topology.worker.childopts}
```
I'm not 100% sure why this is happening but my initial thought is to take a closer look at aef84636a3427da20b1d54acfe1b8de23e2aaf97.

**Comment by JonZeolla** [comment]
Looks like this is fixed in #506

**Comment by JonZeolla** [comment]
Now that master is cleaned up I gave this a shot under 2.2.2.0 and 2.0.0.2.  Looks good to me - spun up full dev on both, checked kibana, etc.

+1

**Pull request closed without merging**
